// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * 无
		 */
		none: string
		/**
		 * 是
		 */
		yes: string
		/**
		 * 否
		 */
		no: string
		/**
		 * 正​常
		 */
		ok: string
		/**
		 * 异​常
		 */
		unhealthy: string
		/**
		 * 暂​无
		 */
		unavailable: string
		/**
		 * 关​闭
		 */
		close: string
		/**
		 * 当​前
		 */
		current: string
		/**
		 * 默​认​模​型
		 */
		defaultModel: string
		/**
		 * 默​认
		 */
		'default': string
		/**
		 * 配​置
		 */
		configured: string
		/**
		 * 生​效
		 */
		effective: string
	}
	status: {
		/**
		 * 服​务​状​态
		 */
		title: string
		/**
		 * 桥​接​状​态​：
		 */
		bridgeState: string
		/**
		 * 平​台​连​通​：
		 */
		platformConnectivity: string
		/**
		 * 配​置​完​成​：
		 */
		setupComplete: string
		/**
		 * C​o​d​e​x​ ​可​用​：
		 */
		codexAvailable: string
		/**
		 * 当​前​会​话​：
		 */
		currentSession: string
		/**
		 * 最​近​检​查​：
		 */
		lastChecked: string
		/**
		 * 问​题​：
		 */
		issues: string
	}
	where: {
		/**
		 * 当​前​会​话
		 */
		title: string
		/**
		 * 会​话​名​：
		 */
		sessionName: string
		/**
		 * 项​目​：
		 */
		project: string
		/**
		 * 路​径​：
		 */
		path: string
		/**
		 * 状​态​：
		 */
		state: string
		/**
		 * 模​型​配​置​：
		 */
		modelConfigured: string
		/**
		 * 模​型​生​效​：
		 */
		modelEffective: string
		/**
		 * B​r​i​d​g​e​ ​会​话​ ​I​D​：
		 */
		bridgeSessionId: string
		/**
		 * C​o​d​e​x​ ​线​程​ ​I​D​：
		 */
		codexThreadId: string
		/**
		 * 最​近​ ​T​u​r​n​ ​I​D​：
		 */
		lastTurnId: string
		/**
		 * 上​次​结​果​：
		 */
		lastResult: string
		/**
		 * 当​前​没​有​活​动​会​话​。
		 */
		noActiveSession: string
		/**
		 * 尚​未​创​建​（​首​次​发​送​任​务​后​生​成​）
		 */
		threadNotCreated: string
	}
	sessions: {
		/**
		 * 最​近​会​话
		 */
		recentTitle: string
		/**
		 * 已​归​档​会​话
		 */
		archivedTitle: string
		/**
		 * 暂​无​会​话​。
		 */
		empty: string
	}
	sessionState: {
		/**
		 * 执​行​中
		 */
		running: string
		/**
		 * 已​中​断
		 */
		interrupted: string
		/**
		 * 失​败
		 */
		failed: string
		/**
		 * 空​闲
		 */
		idle: string
		/**
		 * 上​次​已​完​成
		 */
		lastCompleted: string
		/**
		 * 上​次​已​中​断
		 */
		lastInterrupted: string
		/**
		 * 上​次​失​败
		 */
		lastFailed: string
		/**
		 * 桥​接​服​务​重​启
		 */
		failureBridgeRestart: string
		/**
		 * C​o​d​e​x​ ​服​务​断​开
		 */
		failureAppServerLost: string
		/**
		 * 执​行​失​败
		 */
		failureTurnFailed: string
		/**
		 * 未​知​原​因
		 */
		failureUnknown: string
	}
	commands: {
		/**
		 * 可​用​指​令
		 */
		heading: string
		groups: {
			/**
			 * 帮​助​与​状​态
			 */
			helpStatus: string
			/**
			 * 会​话​与​项​目
			 */
			sessionProject: string
			/**
			 * C​o​d​e​x
			 */
			codex: string
			/**
			 * 控​制
			 */
			control: string
		}
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * 无
		 */
		none: () => LocalizedString
		/**
		 * 是
		 */
		yes: () => LocalizedString
		/**
		 * 否
		 */
		no: () => LocalizedString
		/**
		 * 正常
		 */
		ok: () => LocalizedString
		/**
		 * 异常
		 */
		unhealthy: () => LocalizedString
		/**
		 * 暂无
		 */
		unavailable: () => LocalizedString
		/**
		 * 关闭
		 */
		close: () => LocalizedString
		/**
		 * 当前
		 */
		current: () => LocalizedString
		/**
		 * 默认模型
		 */
		defaultModel: () => LocalizedString
		/**
		 * 默认
		 */
		'default': () => LocalizedString
		/**
		 * 配置
		 */
		configured: () => LocalizedString
		/**
		 * 生效
		 */
		effective: () => LocalizedString
	}
	status: {
		/**
		 * 服务状态
		 */
		title: () => LocalizedString
		/**
		 * 桥接状态：
		 */
		bridgeState: () => LocalizedString
		/**
		 * 平台连通：
		 */
		platformConnectivity: () => LocalizedString
		/**
		 * 配置完成：
		 */
		setupComplete: () => LocalizedString
		/**
		 * Codex 可用：
		 */
		codexAvailable: () => LocalizedString
		/**
		 * 当前会话：
		 */
		currentSession: () => LocalizedString
		/**
		 * 最近检查：
		 */
		lastChecked: () => LocalizedString
		/**
		 * 问题：
		 */
		issues: () => LocalizedString
	}
	where: {
		/**
		 * 当前会话
		 */
		title: () => LocalizedString
		/**
		 * 会话名：
		 */
		sessionName: () => LocalizedString
		/**
		 * 项目：
		 */
		project: () => LocalizedString
		/**
		 * 路径：
		 */
		path: () => LocalizedString
		/**
		 * 状态：
		 */
		state: () => LocalizedString
		/**
		 * 模型配置：
		 */
		modelConfigured: () => LocalizedString
		/**
		 * 模型生效：
		 */
		modelEffective: () => LocalizedString
		/**
		 * Bridge 会话 ID：
		 */
		bridgeSessionId: () => LocalizedString
		/**
		 * Codex 线程 ID：
		 */
		codexThreadId: () => LocalizedString
		/**
		 * 最近 Turn ID：
		 */
		lastTurnId: () => LocalizedString
		/**
		 * 上次结果：
		 */
		lastResult: () => LocalizedString
		/**
		 * 当前没有活动会话。
		 */
		noActiveSession: () => LocalizedString
		/**
		 * 尚未创建（首次发送任务后生成）
		 */
		threadNotCreated: () => LocalizedString
	}
	sessions: {
		/**
		 * 最近会话
		 */
		recentTitle: () => LocalizedString
		/**
		 * 已归档会话
		 */
		archivedTitle: () => LocalizedString
		/**
		 * 暂无会话。
		 */
		empty: () => LocalizedString
	}
	sessionState: {
		/**
		 * 执行中
		 */
		running: () => LocalizedString
		/**
		 * 已中断
		 */
		interrupted: () => LocalizedString
		/**
		 * 失败
		 */
		failed: () => LocalizedString
		/**
		 * 空闲
		 */
		idle: () => LocalizedString
		/**
		 * 上次已完成
		 */
		lastCompleted: () => LocalizedString
		/**
		 * 上次已中断
		 */
		lastInterrupted: () => LocalizedString
		/**
		 * 上次失败
		 */
		lastFailed: () => LocalizedString
		/**
		 * 桥接服务重启
		 */
		failureBridgeRestart: () => LocalizedString
		/**
		 * Codex 服务断开
		 */
		failureAppServerLost: () => LocalizedString
		/**
		 * 执行失败
		 */
		failureTurnFailed: () => LocalizedString
		/**
		 * 未知原因
		 */
		failureUnknown: () => LocalizedString
	}
	commands: {
		/**
		 * 可用指令
		 */
		heading: () => LocalizedString
		groups: {
			/**
			 * 帮助与状态
			 */
			helpStatus: () => LocalizedString
			/**
			 * 会话与项目
			 */
			sessionProject: () => LocalizedString
			/**
			 * Codex
			 */
			codex: () => LocalizedString
			/**
			 * 控制
			 */
			control: () => LocalizedString
		}
	}
}

export type Formatters = {}
