// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * 无
		 */
		none: string
		/**
		 * 是
		 */
		yes: string
		/**
		 * 否
		 */
		no: string
		/**
		 * 正​常
		 */
		ok: string
		/**
		 * 异​常
		 */
		unhealthy: string
		/**
		 * 暂​无
		 */
		unavailable: string
		/**
		 * 关​闭
		 */
		close: string
		/**
		 * 返​回
		 */
		back: string
		/**
		 * 当​前
		 */
		current: string
		/**
		 * 空​槽​位
		 */
		emptySlot: string
		/**
		 * 默​认​模​型
		 */
		defaultModel: string
		/**
		 * 默​认
		 */
		'default': string
		/**
		 * 配​置
		 */
		configured: string
		/**
		 * 生​效
		 */
		effective: string
		/**
		 * ；
		 */
		separator: string
		/**
		 * 其​他
		 */
		other: string
		/**
		 * 上​一​页
		 */
		previousPage: string
		/**
		 * 下​一​页
		 */
		nextPage: string
		/**
		 * 上​一​页
		 */
		previous: string
		/**
		 * 下​一​页
		 */
		next: string
		/**
		 * 待​处​理
		 */
		pending: string
		/**
		 * 未​完​成
		 */
		incomplete: string
		/**
		 * 命​令
		 */
		commands: string
	}
	status: {
		/**
		 * 服​务​状​态
		 */
		title: string
		/**
		 * 桥​接​状​态​：
		 */
		bridgeState: string
		/**
		 * 平​台​连​通​：
		 */
		platformConnectivity: string
		/**
		 * 配​置​完​成​：
		 */
		setupComplete: string
		/**
		 * C​o​d​e​x​ ​可​用​：
		 */
		codexAvailable: string
		/**
		 * 当​前​会​话​：
		 */
		currentSession: string
		/**
		 * 最​近​检​查​：
		 */
		lastChecked: string
		/**
		 * 问​题​：
		 */
		issues: string
	}
	where: {
		/**
		 * 当​前​会​话
		 */
		title: string
		/**
		 * 会​话​名​：
		 */
		sessionName: string
		/**
		 * 项​目​：
		 */
		project: string
		/**
		 * 路​径​：
		 */
		path: string
		/**
		 * 状​态​：
		 */
		state: string
		/**
		 * 模​型​配​置​：
		 */
		modelConfigured: string
		/**
		 * 模​型​生​效​：
		 */
		modelEffective: string
		/**
		 * B​r​i​d​g​e​ ​会​话​ ​I​D​：
		 */
		bridgeSessionId: string
		/**
		 * C​o​d​e​x​ ​线​程​ ​I​D​：
		 */
		codexThreadId: string
		/**
		 * 最​近​ ​T​u​r​n​ ​I​D​：
		 */
		lastTurnId: string
		/**
		 * 上​次​结​果​：
		 */
		lastResult: string
		/**
		 * 当​前​没​有​活​动​会​话​。
		 */
		noActiveSession: string
		/**
		 * 尚​未​创​建​（​首​次​发​送​任​务​后​生​成​）
		 */
		threadNotCreated: string
	}
	sessions: {
		/**
		 * 最​近​会​话
		 */
		recentTitle: string
		/**
		 * 已​归​档​会​话
		 */
		archivedTitle: string
		/**
		 * 已​批​量​归​档​会​话
		 */
		batchArchivedTitle: string
		/**
		 * 暂​无​会​话​。
		 */
		empty: string
		/**
		 * [​当​前​]​ 
		 */
		currentMarker: string
		/**
		 * 暂​无​会​话​。
		 */
		resumeEmpty: string
		/**
		 * 可​恢​复​的​ ​C​o​d​e​x​ ​会​话
		 */
		resumeTitle: string
	}
	sessionState: {
		/**
		 * 执​行​中
		 */
		running: string
		/**
		 * 已​中​断
		 */
		interrupted: string
		/**
		 * 失​败
		 */
		failed: string
		/**
		 * 空​闲
		 */
		idle: string
		/**
		 * 准​备​中
		 */
		starting: string
		/**
		 * 等​待​中
		 */
		blocked: string
		/**
		 * 上​次​已​完​成
		 */
		lastCompleted: string
		/**
		 * 上​次​已​中​断
		 */
		lastInterrupted: string
		/**
		 * 上​次​失​败
		 */
		lastFailed: string
		/**
		 * 桥​接​服​务​重​启
		 */
		failureBridgeRestart: string
		/**
		 * C​o​d​e​x​ ​服​务​断​开
		 */
		failureAppServerLost: string
		/**
		 * 执​行​失​败
		 */
		failureTurnFailed: string
		/**
		 * 未​知​原​因
		 */
		failureUnknown: string
		/**
		 * 未​知
		 */
		unknown: string
	}
	projects: {
		/**
		 * 选​择​要​新​建​会​话​的​项​目
		 */
		pickerTitle: string
		/**
		 * 还​没​有​最​近​项​目​，​请​浏​览​目​录​或​手​动​输​入​路​径​。
		 */
		empty: string
		/**
		 * 浏​览​目​录
		 */
		browseDirectory: string
		/**
		 * 手​动​输​入​路​径
		 */
		enterPath: string
		/**
		 * 返​回​项​目​列​表
		 */
		backToProjects: string
		/**
		 * 选​择​要​浏​览​的​根​目​录
		 */
		selectRoot: string
		/**
		 * 请​发​送​要​开​始​会​话​的​目​录​路​径​，​例​如​：​/​h​o​m​e​/​u​b​u​n​t​u​/​R​e​p​o​/​o​p​e​n​c​l​a​w​
	​发​送​ ​/​c​a​n​c​e​l​ ​返​回​项​目​列​表​。
		 */
		manualPathPrompt: string
		/**
		 * 要​在​这​个​目​录​中​新​建​会​话​吗​？
		 */
		confirmNewSession: string
		/**
		 * 确​认​新​建​会​话
		 */
		confirmNewSessionButton: string
		/**
		 * 这​个​入​口​已​下​线​。​请​使​用​浏​览​目​录​或​手​动​输​入​路​径​。
		 */
		offlineEntry: string
		/**
		 * 已​新​建​会​话
		 */
		newSessionCreated: string
		/**
		 * 已​切​换​会​话
		 */
		sessionSwitched: string
		/**
		 * 已​恢​复​ ​C​o​d​e​x​ ​会​话
		 */
		codexSessionResumed: string
		/**
		 * 当​前​项​目​：
		 */
		currentProject: string
		/**
		 * 已​归​档​会​话
		 */
		archivedSession: string
		/**
		 * 已​归​档​：
		 */
		batchArchived: string
		/**
		 * 已​跳​过​运​行​中​：
		 */
		batchSkippedRunning: string
		/**
		 * 失​败​：
		 */
		batchFailed: string
		/**
		 * 已​恢​复​会​话
		 */
		sessionRestored: string
		/**
		 * 当​前​会​话​已​重​命​名​为​：
		 */
		sessionRenamed: string
		/**
		 * 当​前​项​目​别​名​已​更​新​为​：
		 */
		projectAliasRenamed: string
		/**
		 * 已​清​除​项​目​别​名​：
		 */
		projectAliasCleared: string
		/**
		 * 已​收​藏​项​目​：
		 */
		projectFavorited: string
		/**
		 * 当​前​没​有​活​动​会​话​，​请​发​送​ ​/​n​e​w​ ​选​择​项​目​。
		 */
		noActiveSession: string
		/**
		 * 重​命​名​会​话
		 */
		renameSession: string
		/**
		 * 设​置​项​目​别​名
		 */
		setProjectAlias: string
		/**
		 * 清​除​项​目​别​名
		 */
		clearProjectAlias: string
		groups: {
			/**
			 * 已​收​藏
			 */
			pinned: string
			/**
			 * 最​近​使​用
			 */
			recent: string
		}
		badges: {
			/**
			 * 最​近
			 */
			recent: string
			/**
			 * 本​地​发​现
			 */
			locallyDiscovered: string
			/**
			 * 有​历​史​会​话
			 */
			hasHistory: string
		}
	}
	model: {
		/**
		 * 选​择​模​型
		 */
		selectModel: string
		/**
		 * 选​择​思​考​强​度
		 */
		selectEffort: string
		/**
		 * 先​选​模​型​，​再​按​该​模​型​支​持​情​况​选​择​思​考​强​度​。
		 */
		modelTip: string
		/**
		 * 仅​展​示​这​个​模​型​实​际​支​持​的​档​位​。
		 */
		effortTip: string
		/**
		 * 已​关​闭​模​型​选​择
		 */
		modelPickerClosed: string
		/**
		 * 要​修​改​哪​个​名​称​？
		 */
		editWhichName: string
		/**
		 * 已​配​置
		 */
		configuredMarker: string
		/**
		 * 生​效
		 */
		effectiveMarker: string
		/**
		 * 清​除​模​型​/​强​度​覆​盖
		 */
		clearOverride: string
		/**
		 * 页
		 */
		pageLabel: string
		/**
		 * 个
		 */
		countUnit: string
		/**
		 * 当​前
		 */
		current: string
		/**
		 * 默​认
		 */
		defaultAlias: string
		/**
		 * 默​认​模​型​ ​+​ ​默​认
		 */
		defaultSelectionLabel: string
	}
	commands: {
		/**
		 * 可​用​指​令
		 */
		heading: string
		groups: {
			/**
			 * 帮​助​与​状​态
			 */
			helpStatus: string
			/**
			 * 会​话​与​项​目
			 */
			sessionProject: string
			/**
			 * C​o​d​e​x
			 */
			codex: string
			/**
			 * 控​制
			 */
			control: string
		}
	}
	commandPanel: {
		/**
		 * 打​开​命​令​面​板
		 */
		openPanel: string
		/**
		 * 快​捷​指​令
		 */
		title: string
		/**
		 * 点​击​按​钮​即​可​执​行​桥​接​指​令​。
		 */
		tapToRun: string
		/**
		 * 当​前​快​捷​指​令​：
		 */
		selectedLabel: string
		/**
		 * 当​前​还​没​有​已​配​置​的​快​捷​指​令​。
		 */
		noCommands: string
		/**
		 * 完​整​帮​助
		 */
		fullHelp: string
		/**
		 * 编​辑​快​捷​指​令
		 */
		editCommands: string
		/**
		 * 编​辑​快​捷​指​令
		 */
		editTitle: string
		/**
		 * 点​击​按​钮​进​行​选​择​或​移​除​。​选​择​顺​序​就​是​显​示​顺​序​。
		 */
		editHint: string
		/**
		 * 新​选​中​的​指​令​会​追​加​到​末​尾​。
		 */
		editAppendHint: string
		/**
		 * 当​前​分​组​：
		 */
		currentGroup: string
		/**
		 * 已​选​指​令​：
		 */
		selectedCommands: string
		/**
		 * 当​前​还​没​有​选​中​的​快​捷​指​令​。
		 */
		noSelected: string
		/**
		 * 分​组​页​码​：
		 */
		groupPage: string
		/**
		 * 总​页​码​：
		 */
		totalPage: string
		/**
		 * 保​存
		 */
		save: string
		/**
		 * 恢​复​默​认
		 */
		restoreDefault: string
	}
	browser: {
		/**
		 * 文​件​浏​览
		 */
		title: string
		/**
		 * 当​前​项​目​：
		 */
		project: string
		/**
		 * 当​前​位​置​：
		 */
		location: string
		/**
		 * 页​码​：
		 */
		page: string
		/**
		 * 模​式​：
		 */
		mode: string
		/**
		 * 只​读​浏​览
		 */
		readonly: string
		/**
		 * 项​目​根
		 */
		root: string
		/**
		 * 当​前​目​录​为​空​。
		 */
		empty: string
		/**
		 * 上​一​级
		 */
		up: string
		/**
		 * 回​到​项​目​根
		 */
		backToRoot: string
		/**
		 * 刷​新
		 */
		refresh: string
		/**
		 * 在​当​前​目​录​新​建​会​话
		 */
		useCurrentDirectory: string
		/**
		 * 文​件​预​览
		 */
		previewTitle: string
		/**
		 * 文​件​：
		 */
		file: string
		/**
		 * 路​径​：
		 */
		path: string
		/**
		 * 大​小​：
		 */
		size: string
		/**
		 * 修​改​时​间​：
		 */
		modified: string
		/**
		 * 预​览​页​：
		 */
		previewPage: string
		/**
		 * 仅​预​览​前​ ​4​8​ ​K​B​。
		 */
		previewTruncated: string
		/**
		 * 返​回​目​录
		 */
		returnToDirectory: string
		/**
		 * 文​件​信​息
		 */
		infoTitle: string
		/**
		 * 类​型​：
		 */
		type: string
		/**
		 * 二​进​制​或​暂​不​支​持​预​览
		 */
		binary: string
		/**
		 * 图​片​预​览
		 */
		imagePreview: string
		/**
		 * 确​认​新​建​会​话
		 */
		confirmNewSession: string
		/**
		 * 目​录​：
		 */
		directory: string
		/**
		 * 显​示​名​：
		 */
		displayName: string
		/**
		 * 要​在​这​个​目​录​新​建​会​话​吗​？
		 */
		confirmNewInDirectory: string
		/**
		 * 返​回​目​录
		 */
		backToDirectory: string
	}
	finalAnswer: {
		/**
		 * 展​开​全​文
		 */
		expandFull: string
		/**
		 * 收​起
		 */
		collapse: string
		/**
		 * 实​施​这​个​计​划
		 */
		implementPlan: string
		/**
		 * 最​近​输​出
		 */
		recentOutput: string
		/**
		 * 点​击​「​展​开​最​近​输​出​」​查​看​该​会​话​最​近​一​次​输​出​。
		 */
		expandRecentOutputHint: string
		/**
		 * 该​会​话​还​没​有​最​近​输​出​。
		 */
		noRecentOutput: string
		/**
		 * 展​开​最​近​输​出
		 */
		expandRecentOutput: string
		/**
		 * 收​起​最​近​输​出
		 */
		collapseRecentOutput: string
		/**
		 * 展​开​方​案
		 */
		expandPlan: string
		/**
		 * 收​起​方​案
		 */
		collapsePlan: string
		/**
		 * 已​开​始​实​施​。
		 */
		planConsumed: string
		/**
		 * 最​终​答​复​暂​未​送​达​。​点​击​“​展​开​全​文​”​重​新​渲​染​。
		 */
		finalAnswerDeferred: string
		/**
		 * 方​案​结​果​暂​未​送​达​。​点​击​“​展​开​方​案​”​重​新​渲​染​。
		 */
		planResultDeferred: string
		/**
		 * 已​折​叠​，​共​ 
		 */
		collapsedMultiPagePrefix: string
		/**
		 *  ​页​，​点​击
		 */
		collapsedMultiPageMiddle: string
		/**
		 * 查​看​。
		 */
		collapsedMultiPageSuffix: string
		/**
		 * 已​折​叠​，​点​击
		 */
		collapsedSinglePrefix: string
		/**
		 * 查​看​剩​余​内​容​。
		 */
		collapsedSingleSuffix: string
		/**
		 * 第​ 
		 */
		pagePrefix: string
		/**
		 *  ​页
		 */
		pageSuffix: string
	}
	shared: {
		/**
		 * 刚​刚
		 */
		justNow: string
		/**
		 * 分​钟​前
		 */
		minutesAgo: string
		/**
		 * 小​时​前
		 */
		hoursAgo: string
		/**
		 * 天​前
		 */
		daysAgo: string
		/**
		 * 关​闭
		 */
		effortNone: string
		/**
		 * 极​省
		 */
		effortMinimal: string
		/**
		 * 低
		 */
		effortLow: string
		/**
		 * 中
		 */
		effortMedium: string
		/**
		 * 高
		 */
		effortHigh: string
		/**
		 * 极​高
		 */
		effortXhigh: string
	}
	runtime: {
		/**
		 * 运​行​状​态
		 */
		statusTitle: string
		/**
		 * 状​态
		 */
		state: string
		/**
		 * 进​度
		 */
		progress: string
		/**
		 * 会​话
		 */
		session: string
		/**
		 * 收​起​计​划​清​单
		 */
		hidePlan: string
		/**
		 * 收​起​ ​A​g​e​n​t
		 */
		hideAgents: string
		/**
		 * 计​划​清​单​:
		 */
		planLabel: string
		/**
		 * A​g​e​n​t​:
		 */
		agentsLabel: string
		/**
		 * 计​划​详​情
		 */
		planDetails: string
		/**
		 * 协​作​ ​A​g​e​n​t
		 */
		collabAgents: string
		/**
		 * 查​看​中
		 */
		viewing: string
		/**
		 * 当​前​输​入
		 */
		currentInput: string
		/**
		 * 当​前
		 */
		current: string
		/**
		 * 查​看​详​情
		 */
		inspect: string
		/**
		 * 命​令
		 */
		commands: string
		/**
		 * 中​断​操​作
		 */
		interrupt: string
		/**
		 * 当​前​查​看​中​的​会​话
		 */
		currentViewedSession: string
		/**
		 * 其​他​运​行​中​的​会​话
		 */
		otherRunningSessions: string
		/**
		 * 最​近​结​束​的​会​话
		 */
		recentEndedSessions: string
		/**
		 * 当​前​输​入​会​话
		 */
		currentInputSession: string
		/**
		 * 当​前​查​看​中​的​运​行​会​话
		 */
		focusedRunningSession: string
		/**
		 * 当​前​查​看​中​的​会​话
		 */
		focusedSession: string
		/**
		 * 其​他​会​话
		 */
		otherSessions: string
		/**
		 * 最​近​结​束​的​会​话
		 */
		recentTerminalSessions: string
		/**
		 * �​�​ ​提​示​：​需​要​查​看​运​行​卡​片​时​，​可​发​送​ ​/​h​u​b​。
		 */
		hubTip: string
		/**
		 * �​�​ ​提​示​：​使​用​ ​/​i​n​s​p​e​c​t​ ​查​看​详​情​，​使​用​ ​/​i​n​t​e​r​r​u​p​t​ ​打​断​，​使​用​ ​/​s​t​a​t​u​s​ ​查​看​状​态​。
		 */
		surfaceFooter: string
		/**
		 * �​�​ ​/​s​t​a​t​u​s​ ​|​ ​/​i​n​s​p​e​c​t​ ​|​ ​/​i​n​t​e​r​r​u​p​t
		 */
		hubFooter: string
		/**
		 * 确​认​中​断
		 */
		confirmInterruptTitle: string
		/**
		 * 要​停​止​当​前​正​在​运​行​的​操​作​吗​？
		 */
		confirmInterruptText: string
		/**
		 * 计​划​清​单
		 */
		planEntry: string
		fields: {
			/**
			 * 模​型​名
			 */
			modelName: string
			/**
			 * 模​型​ ​+​ ​推​理​强​度
			 */
			modelWithReasoning: string
			/**
			 * 当​前​目​录
			 */
			currentDir: string
			/**
			 * 项​目​根​目​录
			 */
			projectRoot: string
			/**
			 * G​i​t​ ​分​支
			 */
			gitBranch: string
			/**
			 * 剩​余​上​下​文
			 */
			contextRemaining: string
			/**
			 * 已​用​上​下​文
			 */
			contextUsed: string
			/**
			 * 5​ ​小​时​额​度
			 */
			fiveHourLimit: string
			/**
			 * 周​额​度
			 */
			weeklyLimit: string
			/**
			 * C​o​d​e​x​ ​版​本
			 */
			codexVersion: string
			/**
			 * 上​下​文​窗​口​大​小
			 */
			contextWindowSize: string
			/**
			 * 已​用​ ​T​o​k​e​n
			 */
			usedTokens: string
			/**
			 * 累​计​输​入​ ​T​o​k​e​n
			 */
			totalInputTokens: string
			/**
			 * 累​计​输​出​ ​T​o​k​e​n
			 */
			totalOutputTokens: string
			/**
			 * 会​话​ ​I​D
			 */
			sessionId: string
			/**
			 * 会​话​名
			 */
			sessionName: string
			/**
			 * 项​目​名
			 */
			projectName: string
			/**
			 * 项​目​路​径​（​旧​）
			 */
			projectPath: string
			/**
			 * P​l​a​n​ ​m​o​d​e
			 */
			planMode: string
			/**
			 * 模​型​ ​+​ ​强​度​（​旧​）
			 */
			modelReasoning: string
			/**
			 * 线​程​ ​I​D​（​旧​）
			 */
			threadId: string
			/**
			 * T​u​r​n​ ​I​D
			 */
			turnId: string
			/**
			 * 阻​塞​原​因
			 */
			blockedReason: string
			/**
			 * 当​前​步​骤
			 */
			currentStep: string
			/**
			 * 本​次​ ​T​o​k​e​n
			 */
			lastTokenUsage: string
			/**
			 * 累​计​ ​T​o​k​e​n
			 */
			totalTokenUsage: string
			/**
			 * 上​下​文​窗​口
			 */
			contextWindow: string
			/**
			 * 最​终​答​复​已​就​绪
			 */
			finalAnswerReady: string
		}
		preferences: {
			/**
			 * 已​应​用​ ​R​u​n​t​i​m​e​ ​卡​片​字​段
			 */
			appliedTitle: string
			/**
			 * 当​前​字​段​：
			 */
			currentFields: string
			/**
			 * 已​关​闭​ ​R​u​n​t​i​m​e​ ​卡​片​字​段​选​择
			 */
			closedTitle: string
			/**
			 * R​u​n​t​i​m​e​ ​卡​片​字​段
			 */
			title: string
			/**
			 * 按​按​钮​选​择​要​显​示​的​字​段​。
			 */
			hint: string
			/**
			 * 选​择​顺​序​就​是​显​示​顺​序​；​新​选​中​的​字​段​会​追​加​到​末​尾​。
			 */
			orderHint: string
			/**
			 * 当​前​分​组​：
			 */
			currentGroup: string
			/**
			 * 已​选​字​段​：
			 */
			selectedFields: string
			/**
			 * 当​前​没​有​已​选​字​段​。
			 */
			noSelectedFields: string
			/**
			 * 分​组​页​码​：
			 */
			groupPage: string
			/**
			 * 总​页​码​：
			 */
			totalPage: string
			/**
			 * 保​存​并​应​用
			 */
			save: string
			/**
			 * 恢​复​默​认
			 */
			reset: string
		}
		planStatus: {
			/**
			 * 进​行​中
			 */
			inProgress: string
			/**
			 * 已​完​成
			 */
			completed: string
			/**
			 * 待​处​理
			 */
			pending: string
			/**
			 * 失​败
			 */
			failed: string
			/**
			 * 阻​塞​中
			 */
			blocked: string
		}
		agentStatus: {
			/**
			 * 等​待​初​始​化
			 */
			pendingInit: string
			/**
			 * 运​行​中
			 */
			running: string
			/**
			 * 已​完​成
			 */
			completed: string
			/**
			 * 异​常
			 */
			errored: string
			/**
			 * 已​停​止
			 */
			stopped: string
			/**
			 * 未​找​到
			 */
			notFound: string
			/**
			 * 等​待​状​态​更​新
			 */
			waitingForUpdate: string
		}
		interactionState: {
			/**
			 * 待​处​理
			 */
			pending: string
			/**
			 * 等​待​文​字​回​答
			 */
			awaitingText: string
			/**
			 * 已​处​理
			 */
			answered: string
			/**
			 * 已​取​消
			 */
			canceled: string
			/**
			 * 已​过​期
			 */
			expired: string
			/**
			 * 处​理​失​败
			 */
			failed: string
		}
		interaction: {
			/**
			 * 类​型​：
			 */
			type: string
			/**
			 * 内​容​：
			 */
			body: string
			/**
			 * 说​明​：
			 */
			detail: string
			/**
			 * 取​消​本​次​交​互
			 */
			cancelInteraction: string
			/**
			 * 问​题​：
			 */
			questionLabel: string
			/**
			 * 标​题​：
			 */
			headerLabel: string
			/**
			 * 这​条​回​答​会​按​敏​感​输​入​处​理​，​不​会​进​入​可​见​摘​要​。
			 */
			secretNotice: string
			/**
			 * 当​前​正​在​等​待​你​直​接​发​送​这​条​问​题​的​文​字​回​答​。
			 */
			awaitingTextNotice: string
			/**
			 * 点​击​下​方​按​钮​后​，​直​接​在​聊​天​里​发​送​你​的​回​答​。
			 */
			sendTextPrompt: string
			/**
			 * 发​送​文​字​回​答
			 */
			sendTextAnswer: string
			/**
			 * 状​态​：
			 */
			stateLabel: string
			/**
			 * 结​果​：
			 */
			resultLabel: string
			/**
			 * 已​提​交​回​答
			 */
			submittedAnswers: string
			/**
			 * 收​起​已​提​交​回​答
			 */
			collapseAnswers: string
			/**
			 * 查​看​已​提​交​回​答
			 */
			expandAnswers: string
			/**
			 * 已​过​期
			 */
			expiredLabel: string
		}
		inspectSection: {
			/**
			 * 详​情​已​折​叠​，​点​击​按​钮​展​开​。
			 */
			collapseHint: string
			/**
			 * 展​开​详​情
			 */
			expandDetails: string
			/**
			 * 收​起​详​情
			 */
			collapseDetails: string
			/**
			 * 详​情​页​：
			 */
			detailPage: string
			/**
			 * 当​前​任​务​详​情
			 */
			currentTaskDetails: string
			/**
			 * 会​话​：
			 */
			session: string
			/**
			 * 项​目​：
			 */
			project: string
			/**
			 * 状​态​：
			 */
			state: string
			/**
			 * 阻​塞​原​因​：
			 */
			blockedReason: string
			/**
			 * 当​前​动​作​：
			 */
			currentAction: string
			/**
			 * 已​耗​时​：
			 */
			elapsedTime: string
			/**
			 * 最​近​结​论​：
			 */
			recentConclusion: string
			/**
			 * 最​终​答​复​：
			 */
			finalAnswerReady: string
			/**
			 * 已​就​绪
			 */
			ready: string
			/**
			 * 说​明​：
			 */
			note: string
			/**
			 * 最​近​动​作
			 */
			recentActions: string
			/**
			 * 最​近​命​令
			 */
			recentCommands: string
			/**
			 * 最​近​文​件​变​更
			 */
			recentFileChanges: string
			/**
			 * 最​近​工​具​与​搜​索
			 */
			recentToolsAndSearch: string
			/**
			 * 最​近​ ​H​o​o​k
			 */
			recentHooks: string
			/**
			 * 提​示​与​告​警
			 */
			noticesAndWarnings: string
			/**
			 * T​o​k​e​n​ ​用​量
			 */
			tokenUsage: string
			/**
			 * 最​近​差​异
			 */
			recentDiff: string
			/**
			 * 计​划​清​单
			 */
			planList: string
			/**
			 * 方​案​草​稿
			 */
			planDraft: string
			/**
			 * 补​充​说​明
			 */
			supplementaryNotes: string
			/**
			 * 待​处​理​交​互
			 */
			pendingInteractions: string
			/**
			 * 最​近​已​答​交​互
			 */
			recentAnsweredInteractions: string
			/**
			 * 命​令​：
			 */
			commandLabel: string
			/**
			 * 状​态​：
			 */
			commandState: string
			/**
			 * 结​果​：
			 */
			commandResult: string
			/**
			 * 目​录​：
			 */
			commandDirectory: string
			/**
			 * 退​出​码​：
			 */
			commandExitCode: string
			/**
			 * 耗​时​：
			 */
			commandDuration: string
			/**
			 * ，​等​待​文​字​回​答
			 */
			awaitingTextSuffix: string
			/**
			 * 开​始​执​行
			 */
			turnStarted: string
			/**
			 * 执​行​结​束​（
			 */
			turnCompleted: string
			/**
			 * 线​程​阻​塞​（
			 */
			threadBlocked: string
			/**
			 * 线​程​状​态​：
			 */
			threadStatus: string
			/**
			 * 开​始​：
			 */
			itemStarted: string
			/**
			 * 完​成​：
			 */
			itemCompleted: string
		}
		rollback: {
			/**
			 * 选​择​回​滚​目​标
			 */
			selectTarget: string
			/**
			 * 只​展​示​用​户​输​入​，​不​展​示​ ​a​g​e​n​t​ ​输​出​。
			 */
			onlyUserInput: string
			/**
			 * 页​码​：
			 */
			pageLabel: string
			/**
			 * 确​认​回​滚
			 */
			confirmRollback: string
			/**
			 * 目​标​：
			 */
			targetLabel: string
			/**
			 * 将​删​除​的​ ​t​u​r​n​ ​数​：
			 */
			turnCountToDelete: string
			/**
			 * 本​地​文​件​改​动​不​会​自​动​撤​销​。
			 */
			localChangesWarning: string
			/**
			 * 确​认​回​滚
			 */
			confirmButton: string
			/**
			 * 返​回​列​表
			 */
			backToList: string
			/**
			 * 已​关​闭​回​滚​目​标​选​择
			 */
			closedTitle: string
			/**
			 * 未​执​行​回​滚​。
			 */
			notRolledBack: string
			/**
			 * 已​关​闭​活​动​详​情
			 */
			closedInspectTitle: string
			/**
			 * 重​新​发​送​ ​/​i​n​s​p​e​c​t​ ​可​再​次​打​开​。
			 */
			reopenHint: string
		}
		currentStep: {
			/**
			 * 等​待​批​准
			 */
			waitingForApproval: string
			/**
			 * 等​待​输​入
			 */
			waitingForInput: string
			/**
			 * 正​在​更​新​计​划
			 */
			updatingPlan: string
			/**
			 * 正​在​运​行​命​令
			 */
			runningCommand: string
			/**
			 * 正​在​修​改​文​件
			 */
			editingFiles: string
			/**
			 * 正​在​调​用​ ​M​C​P​ ​工​具
			 */
			callingMcpTool: string
			/**
			 * 正​在​进​行​网​页​搜​索
			 */
			webSearch: string
			/**
			 * 正​在​整​理​回​复
			 */
			draftingResponse: string
			/**
			 * 正​在​思​考
			 */
			thinking: string
			/**
			 * 正​在​处​理​任​务
			 */
			processingTask: string
			/**
			 * 等​待​第​一​条​活​动
			 */
			waitingForFirstActivity: string
			/**
			 * 正​在​处​理​中
			 */
			processing: string
			/**
			 * 等​待​继​续
			 */
			waitingToContinue: string
			/**
			 * 当​前​没​有​进​行​中​的​步​骤
			 */
			noActiveStep: string
			/**
			 * 已​中​断​，​没​有​进​行​中​的​步​骤
			 */
			interruptedNoStep: string
			/**
			 * 执​行​失​败​，​没​有​进​行​中​的​步​骤
			 */
			failedNoStep: string
			/**
			 * 等​待​活​动
			 */
			waitingForActivity: string
		}
		milestone: {
			/**
			 * 最​终​答​复​已​生​成
			 */
			replyGenerated: string
		}
		threadStatus: {
			/**
			 * 未​加​载
			 */
			notLoaded: string
			/**
			 * 空​闲
			 */
			idle: string
			/**
			 * 活​跃
			 */
			active: string
			/**
			 * 系​统​错​误
			 */
			systemError: string
		}
		blockedToken: {
			/**
			 * 等​待​批​准
			 */
			waitingOnApproval: string
			/**
			 * 等​待​输​入
			 */
			waitingOnUserInput: string
		}
		commandState: {
			/**
			 * 进​行​中
			 */
			running: string
			/**
			 * 已​完​成
			 */
			completed: string
			/**
			 * 失​败
			 */
			failed: string
			/**
			 * 已​中​断
			 */
			interrupted: string
		}
		optionalLabel: {
			/**
			 * 模​型
			 */
			model: string
			/**
			 * 目​录
			 */
			currentDir: string
		}
		/**
		 * .​.​.​ ​还​有​ 
		 */
		moreStepsPrefix: string
		/**
		 *  ​个​步​骤
		 */
		moreStepsSuffix: string
		/**
		 * .​.​.​ ​还​有​ 
		 */
		moreAgentsPrefix: string
		/**
		 *  ​个​ ​A​g​e​n​t
		 */
		moreAgentsSuffix: string
		/**
		 * .​.​.​ ​还​有​ 
		 */
		morePlanItemsPrefix: string
		/**
		 *  ​项​计​划
		 */
		morePlanItemsSuffix: string
		/**
		 * .​.​.​ ​还​有​ 
		 */
		moreSessionsPrefix: string
		/**
		 *  ​个​会​话​未​显​示
		 */
		moreSessionsSuffix: string
		/**
		 *  ​个​运​行​中
		 */
		agentsRunningSuffix: string
		/**
		 *  ​个
		 */
		selectedFieldCountSuffix: string
		/**
		 * 本​次​：
		 */
		tokenUsageThisPrefix: string
		/**
		 * 累​计​：
		 */
		tokenUsageTotalPrefix: string
		/**
		 * 输​入​ 
		 */
		tokenUsageInput: string
		/**
		 * ，​输​出​ 
		 */
		tokenUsageOutput: string
		/**
		 * ，​缓​存​ 
		 */
		tokenUsageCache: string
		/**
		 * ，​推​理​ 
		 */
		tokenUsageReasoning: string
		/**
		 * 上​下​文​窗​口​：
		 */
		tokenContextWindowPrefix: string
		inspectTurnStatus: {
			/**
			 * 空​闲
			 */
			idle: string
			/**
			 * 准​备​中
			 */
			starting: string
			/**
			 * 执​行​中
			 */
			running: string
			/**
			 * 等​待​中
			 */
			blocked: string
			/**
			 * 已​中​断
			 */
			interrupted: string
			/**
			 * 已​完​成
			 */
			completed: string
			/**
			 * 失​败
			 */
			failed: string
			/**
			 * 未​知
			 */
			unknown: string
		}
	}
	errors: {
		/**
		 * 这​个​按​钮​已​过​期​，​请​重​新​操​作​。
		 */
		buttonExpired: string
		/**
		 * 当​前​正​在​等​待​你​处​理​交​互​卡​片​，​请​先​在​卡​片​中​回​答​或​取​消​。
		 */
		pendingInteractionBlockNotice: string
		/**
		 * 当​前​没​有​活​动​会​话​。
		 */
		noActiveSession: string
		/**
		 * 当​前​项​目​仍​在​执​行​，​请​先​等​待​完​成​或​停​止​当​前​操​作​。
		 */
		projectBusy: string
		/**
		 * 这​个​交​互​已​过​期​。
		 */
		interactionExpired: string
		/**
		 * 这​个​操​作​已​处​理​。
		 */
		operationHandled: string
		/**
		 * C​o​d​e​x​ ​服​务​暂​时​不​可​用​，​请​稍​后​重​试​。
		 */
		codexUnavailable: string
		/**
		 * 这​个​按​钮​已​过​期​，​请​重​新​发​送​ ​/​r​u​n​t​i​m​e​。
		 */
		buttonExpiredRuntime: string
		/**
		 * 当​前​项​目​仍​在​执​行​，​请​等​待​完​成​或​发​送​ ​/​i​n​t​e​r​r​u​p​t​。
		 */
		projectBusyInterrupt: string
		/**
		 * 找​不​到​这​个​会​话​。
		 */
		sessionNotFound: string
		/**
		 * 暂​时​无​法​处​理​这​个​交​互​，​请​稍​后​再​试​。
		 */
		interactionTemporarilyUnavailable: string
		/**
		 * 暂​时​无​法​读​取​这​张​图​片​，​请​稍​后​重​试​。
		 */
		imageReadFailed: string
		/**
		 * 当​前​平​台​正​在​限​流​，​请​稍​后​再​试​。
		 */
		platformRateLimited: string
		/**
		 * 当​前​没​有​正​在​执​行​的​操​作​。
		 */
		noRunningOperation: string
		/**
		 * 暂​时​无​法​更​新​这​条​消​息​，​请​稍​后​再​试​。
		 */
		messageUpdateFailed: string
		/**
		 * 请​先​发​送​ ​/​n​e​w​ ​选​择​项​目​。
		 */
		selectProjectFirst: string
		/**
		 * 这​个​按​钮​已​过​期​，​请​重​新​发​送​ ​/​r​o​l​l​b​a​c​k​。
		 */
		buttonExpiredRollback: string
		/**
		 * 这​个​模​型​列​表​已​过​期​，​请​重​新​发​送​ ​/​m​o​d​e​l​。
		 */
		modelListExpired: string
		/**
		 * 找​不​到​这​个​模​型​，​请​先​发​送​ ​/​m​o​d​e​l​ ​用​按​钮​选​择​。
		 */
		modelNotFound: string
		/**
		 * 当​前​最​多​只​能​并​行​运​行​ 
		 */
		runningCapacityLimitPrefix: string
		/**
		 *  ​个​会​话​，​请​先​等​待​完​成​或​停​止​部​分​任​务​。
		 */
		runningCapacityLimitSuffix: string
		/**
		 * 找​不​到​这​个​技​能​，​请​先​发​送​ ​/​s​k​i​l​l​s​ ​查​看​当​前​项​目​的​技​能​列​表​。
		 */
		skillNotFound: string
		/**
		 * 找​不​到​这​个​插​件​，​请​先​发​送​ ​/​p​l​u​g​i​n​s​ ​查​看​当​前​可​用​列​表​。
		 */
		pluginNotFound: string
		/**
		 * 当​前​项​目​没​有​可​列​出​的​技​能​。
		 */
		noSkillsAvailable: string
		/**
		 * 当​前​项​目​没​有​可​列​出​的​插​件​。
		 */
		noPluginsAvailable: string
		/**
		 * 当​前​没​有​可​列​出​的​ ​A​p​p​s​。
		 */
		noAppsAvailable: string
		/**
		 * 当​前​没​有​可​列​出​的​ ​M​C​P​ ​服​务​器​。
		 */
		noMcpServers: string
		/**
		 * 当​前​无​法​生​成​这​个​ ​M​C​P​ ​服​务​器​的​登​录​链​接​。
		 */
		mcpLoginFailed: string
		/**
		 * 当​前​没​有​可​选​择​的​回​滚​目​标​。
		 */
		noRollbackTarget: string
		/**
		 * 这​个​回​滚​目​标​已​失​效​，​请​重​新​发​送​ ​/​r​o​l​l​b​a​c​k​。
		 */
		rollbackTargetExpired: string
		/**
		 * 当​前​会​话​还​没​有​可​压​缩​的​ ​C​o​d​e​x​ ​线​程​。
		 */
		noThreadToCompact: string
		/**
		 * 当​前​会​话​还​没​有​可​分​叉​的​ ​C​o​d​e​x​ ​线​程​，​请​先​完​成​一​次​任​务​。
		 */
		noThreadToFork: string
		/**
		 * 当​前​会​话​还​没​有​ ​C​o​d​e​x​ ​线​程​，​请​先​完​成​一​次​任​务​。
		 */
		noThreadYet: string
		/**
		 * 当​前​会​话​还​没​有​可​回​滚​的​ ​C​o​d​e​x​ ​线​程​。
		 */
		noThreadToRollback: string
		/**
		 * 当​前​没​有​可​归​档​会​话​。
		 */
		noArchivableSessions: string
		/**
		 * 当​前​无​法​归​档​这​个​会​话​，​请​稍​后​重​试​。
		 */
		archiveTemporarilyUnavailable: string
		/**
		 * 当​前​无​法​恢​复​这​个​会​话​，​请​稍​后​重​试​。
		 */
		resumeTemporarilyUnavailable: string
		/**
		 * 当​前​最​多​只​能​并​行​运​行​ 
		 */
		runningSessionLimitPrefix: string
		/**
		 *  ​个​会​话​，​请​先​等​待​完​成​或​停​止​部​分​任​务​。
		 */
		runningSessionLimitSuffix: string
		/**
		 * 当​前​项​目​还​没​有​设​置​别​名​。
		 */
		noProjectAlias: string
		/**
		 * 这​个​项​目​已​经​收​藏​。
		 */
		projectAlreadyStarred: string
		/**
		 * 当​前​没​有​可​取​消​的​输​入​。
		 */
		noCancellableInput: string
		/**
		 * 当​前​没​有​可​用​的​活​动​详​情​。
		 */
		noActiveDetails: string
		/**
		 * 这​个​ ​C​o​d​e​x​ ​会​话​已​绑​定​到​另​一​个​聊​天​。
		 */
		sessionBoundToAnotherChat: string
		/**
		 * 当​前​没​有​可​浏​览​的​根​目​录​。
		 */
		noBrowsableRoot: string
		/**
		 * 这​个​目​录​不​可​用​，​请​重​新​发​送​目​录​路​径​。​
	​也​可​以​发​送​ ​/​c​a​n​c​e​l​ ​返​回​项​目​列​表​。
		 */
		directoryUnavailable: string
		/**
		 * 桥​接​状​态​未​知​，​请​在​本​机​运​行​ ​c​t​b​ ​d​o​c​t​o​r​。
		 */
		bridgeStateUnknown: string
		/**
		 * 找​不​到​这​个​ ​C​o​d​e​x​ ​会​话​。
		 */
		codexSessionNotFound: string
		/**
		 * 只​支​持​ ​/​a​r​c​h​i​v​e​ ​或​ ​/​a​r​c​h​i​v​e​ ​a​l​l​。
		 */
		archiveOnlyOrAll: string
		/**
		 * 暂​时​无​法​关​闭​这​条​消​息​，​请​稍​后​再​试​。
		 */
		closeMessageFailed: string
		/**
		 * 状​态​存​储​当​前​不​可​用​。
		 */
		stateStoreUnavailable: string
		/**
		 * 暂​时​无​法​打​开​命​令​面​板​，​请​稍​后​重​试​。
		 */
		commandPanelOpenFailed: string
		/**
		 * 暂​时​无​法​打​开​编​辑​器​，​请​稍​后​重​试​。
		 */
		editorOpenFailed: string
		/**
		 * 暂​时​无​法​更​新​编​辑​器​，​请​稍​后​重​试​。
		 */
		editorUpdateFailed: string
		/**
		 * 暂​时​无​法​关​闭​编​辑​器​，​请​稍​后​重​试​。
		 */
		editorCloseFailed: string
		/**
		 * 这​个​指​令​当​前​不​能​加​入​快​捷​指​令​。
		 */
		commandNotAddable: string
		/**
		 * 最​多​只​能​保​留​ ​8​ ​个​快​捷​指​令​。
		 */
		commandShortcutLimit: string
		/**
		 * 至​少​保​留​ ​1​ ​个​快​捷​指​令​。
		 */
		commandShortcutMinimum: string
		/**
		 * 这​个​入​口​已​下​线​。​请​直​接​告​诉​ ​C​o​d​e​x​ ​发​送​图​片​。
		 */
		offlineEntryImage: string
		/**
		 * 这​个​入​口​已​下​线​。​请​直​接​告​诉​ ​C​o​d​e​x​ ​发​送​文​件​。
		 */
		offlineEntryFile: string
		/**
		 * 当​前​没​有​运​行​中​的​会​话​。
		 */
		noRunningSessions: string
		/**
		 * 当​前​有​待​处​理​的​交​互​，​请​先​完​成​当​前​操​作​。
		 */
		pendingInteractionExists: string
		/**
		 * 当​前​无​法​中​断​正​在​运​行​的​操​作​。
		 */
		interruptUnavailable: string
		/**
		 * 当​前​无​法​中​断​这​个​会​话​的​操​作​。
		 */
		interruptUnavailableForSession: string
		/**
		 * 这​次​操​作​未​成​功​完​成​，​请​重​试​。
		 */
		operationIncomplete: string
		/**
		 * 本​次​操​作​已​完​成​，​但​没​有​可​返​回​的​最​终​答​复​。
		 */
		noFinalResponse: string
		/**
		 * 这​个​本​地​图​片​路​径​不​可​用​，​请​确​认​文​件​存​在​且​是​常​见​图​片​格​式​。
		 */
		localImageInvalid: string
		/**
		 * 当​前​无​法​把​附​件​ 
		 */
		attachmentConversionFailedPrefix: string
		/**
		 *  ​转​成​ ​C​o​d​e​x​ ​可​读​输​入​。
		 */
		attachmentConversionFailedSuffix: string
		/**
		 * 最​近​附​件​暂​时​无​法​自​动​转​成​ ​C​o​d​e​x​ ​可​读​输​入​，​请​改​用​支​持​文​本​提​取​的​文​件​，​或​稍​后​再​试​。
		 */
		attachmentAutoConversionFailed: string
		/**
		 * 未​启​用​语​音​输​入​。
		 */
		voiceNotEnabled: string
		/**
		 * 暂​时​无​法​读​取​这​段​语​音​，​请​稍​后​重​试​。
		 */
		voiceReadFailed: string
		/**
		 * 暂​时​无​法​处​理​这​段​语​音​，​请​稍​后​重​试​。
		 */
		voiceProcessingFailed: string
		/**
		 * 这​条​语​音​对​应​的​会​话​已​不​可​用​，​请​重​新​选​择​会​话​后​再​试​。
		 */
		voiceSessionUnavailable: string
		/**
		 * 语​音​已​转​写​，​但​对​应​会​话​已​不​可​用​，​请​重​新​发​送​。
		 */
		voiceTranscribedSessionUnavailable: string
		/**
		 * O​p​e​n​A​I​ ​语​音​转​写​失​败​，​正​在​尝​试​ ​r​e​a​l​t​i​m​e​ ​兜​底​。
		 */
		voiceTranscriptionFailedRealtimeFallback: string
		/**
		 * 当​前​ ​C​o​d​e​x​ ​模​型​不​支​持​ ​r​e​a​l​t​i​m​e​ ​音​频​输​入​。
		 */
		realtimeAudioNotSupported: string
		/**
		 * 系​统​里​找​不​到​ ​f​f​m​p​e​g​：
		 */
		ffmpegNotFoundPrefix: string
		/**
		 * 当​前​会​话​已​经​变​化​，​请​重​新​发​送​结​构​化​输​入​。
		 */
		sessionChanged: string
		/**
		 * 用​法​：​/​s​k​i​l​l​ ​<​技​能​名​>​ ​:​:​ ​任​务​说​明
		 */
		skillUsageHint: string
		/**
		 * 用​法​：​/​p​l​u​g​i​n​ ​i​n​s​t​a​l​l​ ​<​市​场​>​/​<​插​件​名​>
		 */
		pluginInstallUsage: string
		/**
		 * 用​法​：​/​p​l​u​g​i​n​ ​u​n​i​n​s​t​a​l​l​ ​<​插​件​I​D​>
		 */
		pluginUninstallUsage: string
		/**
		 * 用​法​：​/​p​l​u​g​i​n​ ​i​n​s​t​a​l​l​ ​<​市​场​>​/​<​插​件​名​>​ ​或​ ​/​p​l​u​g​i​n​ ​u​n​i​n​s​t​a​l​l​ ​<​插​件​I​D​>
		 */
		pluginUsage: string
		/**
		 * 用​法​：​/​m​c​p​、​/​m​c​p​ ​r​e​l​o​a​d​ ​或​ ​/​m​c​p​ ​l​o​g​i​n​ ​<​名​称​>
		 */
		mcpUsage: string
		/**
		 * 用​法​：​/​m​c​p​ ​l​o​g​i​n​ ​<​名​称​>
		 */
		mcpLoginUsage: string
		/**
		 * 用​法​：​/​r​e​v​i​e​w​ ​[​d​e​t​a​c​h​e​d​]​ ​[​b​r​a​n​c​h​ ​<​分​支​>​|​c​o​m​m​i​t​ ​<​S​H​A​>​|​c​u​s​t​o​m​ ​<​说​明​>​]
		 */
		reviewUsage: string
		/**
		 * 用​法​：​/​r​o​l​l​b​a​c​k​ ​或​ ​/​r​o​l​l​b​a​c​k​ ​<​回​滚​的​ ​t​u​r​n​ ​数​量​>
		 */
		rollbackUsage: string
		/**
		 * 用​法​：​/​t​h​r​e​a​d​ ​n​a​m​e​ ​<​名​称​>​ ​或​ ​/​t​h​r​e​a​d​ ​m​e​t​a​ ​b​r​a​n​c​h​=​<​分​支​>​ ​s​h​a​=​<​提​交​>​ ​o​r​i​g​i​n​=​<​U​R​L​>​ ​或​ ​/​t​h​r​e​a​d​ ​c​l​e​a​n​-​t​e​r​m​i​n​a​l​s
		 */
		threadUsage: string
		/**
		 * 用​法​：​/​t​h​r​e​a​d​ ​n​a​m​e​ ​<​名​称​>
		 */
		threadNameUsage: string
		/**
		 * 用​法​：​/​t​h​r​e​a​d​ ​m​e​t​a​ ​b​r​a​n​c​h​=​<​分​支​>​ ​s​h​a​=​<​提​交​>​ ​o​r​i​g​i​n​=​<​U​R​L​>
		 */
		threadMetaUsage: string
		/**
		 * 用​法​：​/​m​e​n​t​i​o​n​ ​<​p​a​t​h​>​ ​:​:​ ​任​务​说​明
		 */
		mentionUsage: string
		/**
		 * 用​法​：​/​a​t​t​a​c​h​ ​<​附​件​I​D​>​ ​:​:​ ​任​务​说​明
		 */
		attachUsage: string
		/**
		 * 用​法​：​/​l​o​c​a​l​_​i​m​a​g​e​ ​<​图​片​路​径​>​ ​:​:​ ​任​务​说​明
		 */
		localImageUsage: string
		/**
		 * 这​个​问​题​只​能​用​按​钮​回​答​。
		 */
		buttonsOnly: string
		/**
		 * 请​先​切​换​到​这​个​会​话​，​再​发​送​文​字​回​答​。
		 */
		switchSessionBeforeTextReply: string
		/**
		 * 这​个​操​作​当​前​不​支​持​。
		 */
		operationNotSupported: string
		/**
		 * 这​个​问​题​不​能​跳​过​。
		 */
		cannotSkip: string
		/**
		 * 请​输​入​有​效​数​字​。
		 */
		invalidNumber: string
		/**
		 * 请​输​入​整​数​。
		 */
		integerRequired: string
		/**
		 * 请​输​入​ ​t​r​u​e​/​f​a​l​s​e​ ​或​ ​是​/​否​。
		 */
		booleanFormat: string
		/**
		 * 请​至​少​输​入​一​个​值​。
		 */
		atLeastOneValue: string
		/**
		 * 请​先​输​入​至​少​一​个​值​，​或​点​击​跳​过​。
		 */
		atLeastOneValueOrSkip: string
		/**
		 * 回​答​不​能​为​空​。
		 */
		answerRequired: string
		/**
		 * 输​入​值​不​合​法​。
		 */
		invalidValue: string
		/**
		 * 可​用​值​：
		 */
		allowedValuesPrefix: string
		/**
		 * 。
		 */
		allowedValuesSuffix: string
		/**
		 * 当​前​没​有​活​动​会​话​，​请​先​发​送​ ​/​n​e​w​ ​或​ ​/​u​s​e​ ​进​入​项​目​。
		 */
		browserNoSession: string
		/**
		 * 当​前​项​目​目​录​不​可​用​，​请​重​新​选​择​项​目​后​再​试​。
		 */
		browserUnavailableProject: string
		/**
		 * 当​前​浏​览​根​目​录​不​可​用​，​请​重​新​发​送​ ​/​n​e​w​ ​后​重​试​。
		 */
		browserUnavailableRoot: string
		/**
		 * 这​个​按​钮​已​过​期​，​请​重​新​发​送​ ​/​b​r​o​w​s​e​。
		 */
		browserExpired: string
		/**
		 * 这​个​按​钮​已​过​期​，​请​重​新​发​送​ ​/​n​e​w​ ​后​再​浏​览​。
		 */
		browserExpiredPreSession: string
		/**
		 * 当​前​无​法​更​新​这​个​浏​览​消​息​，​请​重​新​发​送​ ​/​b​r​o​w​s​e​。
		 */
		browserUpdateFailed: string
		/**
		 * P​h​a​s​e​ ​1​ ​暂​不​支​持​浏​览​符​号​链​接​。
		 */
		browserSymlinkUnsupported: string
		/**
		 * 当​前​目​录​不​可​用​，​请​重​新​发​送​ ​/​n​e​w​ ​后​重​试​。
		 */
		browserCreateSessionUnavailable: string
		/**
		 * 暂​时​无​法​读​取​这​个​文​件​，​请​稍​后​重​试​。
		 */
		browserFileInfoFailed: string
		/**
		 * 当​前​无​法​关​闭​这​个​浏​览​消​息​。
		 */
		browserCloseFailed: string
		/**
		 * 暂​时​无​法​发​送​这​张​图​片​预​览​，​请​稍​后​重​试​。
		 */
		browserImagePreviewFailed: string
		/**
		 * 模​型​操​作​暂​时​不​可​用​，​请​稍​后​重​试​。
		 */
		modelOperationUnavailable: string
		/**
		 * 技​能​列​表​暂​时​不​可​用​，​请​稍​后​重​试​。
		 */
		skillsListUnavailable: string
		/**
		 * 结​构​化​ ​s​k​i​l​l​ ​输​入​暂​时​不​可​用​，​请​稍​后​重​试​。
		 */
		structuredSkillInputUnavailable: string
		/**
		 * 插​件​列​表​暂​时​不​可​用​，​请​稍​后​重​试​。
		 */
		extensionsListUnavailable: string
		/**
		 * 当​前​无​法​管​理​插​件​，​请​稍​后​重​试​。
		 */
		manageExtensionsUnavailable: string
		/**
		 * 当​前​无​法​读​取​ ​A​p​p​s​ ​列​表​，​请​稍​后​重​试​。
		 */
		appsListUnavailable: string
		/**
		 * 当​前​无​法​读​取​ ​M​C​P​ ​状​态​，​请​稍​后​重​试​。
		 */
		mcpStatusUnavailable: string
		/**
		 * 当​前​无​法​读​取​账​号​状​态​，​请​稍​后​重​试​。
		 */
		accountStatusUnavailable: string
		/**
		 * 当​前​无​法​启​动​审​查​，​请​稍​后​重​试​。
		 */
		reviewUnavailable: string
		/**
		 * 当​前​无​法​分​叉​这​个​会​话​，​请​稍​后​重​试​。
		 */
		forkSessionUnavailable: string
		/**
		 * 当​前​无​法​回​滚​这​个​会​话​，​请​稍​后​重​试​。
		 */
		rollbackSessionUnavailable: string
		/**
		 * 当​前​无​法​清​空​这​个​会​话​的​上​下​文​，​请​稍​后​重​试​。
		 */
		clearContextUnavailable: string
		/**
		 * 当​前​无​法​压​缩​这​个​线​程​，​请​稍​后​重​试​。
		 */
		compactThreadUnavailable: string
		/**
		 * 本​地​图​片​输​入​暂​时​不​可​用​，​请​稍​后​重​试​。
		 */
		localImageInputUnavailable: string
		/**
		 * 结​构​化​引​用​输​入​暂​时​不​可​用​，​请​稍​后​重​试​。
		 */
		structuredReferenceInputUnavailable: string
		/**
		 * 附​件​引​用​暂​时​不​可​用​，​请​稍​后​重​试​。
		 */
		attachmentReferenceUnavailable: string
		/**
		 * 当​前​无​法​更​新​线​程​设​置​，​请​稍​后​重​试​。
		 */
		threadSettingsUnavailable: string
		/**
		 * 当​前​无​法​恢​复​ ​C​o​d​e​x​ ​会​话​，​请​稍​后​重​试​。
		 */
		resumeSessionUnavailable: string
		/**
		 * 当​前​无​法​开​始​实​施​，​请​稍​后​重​试​。
		 */
		implementationUnavailable: string
		/**
		 * 这​台​服​务​器​还​没​有​绑​定
		 */
		serverNotBoundPrefix: string
		/**
		 * 账​号​，​请​等​待​管​理​员​在​本​机​确​认​。
		 */
		serverNotBoundSuffix: string
		/**
		 * 这​个
		 */
		unauthorizedAccountPrefix: string
		/**
		 * 账​号​无​权​访​问​此​服​务​器​上​的​ ​C​o​d​e​x​。
		 */
		unauthorizedAccountSuffix: string
		/**
		 * 这​个​按​钮​已​过​期​，​请​重​新​打​开​编​辑​器​。
		 */
		buttonExpiredReopenEditor: string
		/**
		 * 这​个​按​钮​已​过​期​，​请​重​新​打​开​命​令​面​板​。
		 */
		buttonExpiredReopenPanel: string
		/**
		 * 这​个​按​钮​已​过​期​，​请​重​新​发​送​ ​/​i​n​s​p​e​c​t​。
		 */
		buttonExpiredInspect: string
		/**
		 * 已​保​存​，​但​暂​时​无​法​刷​新​命​令​面​板​。
		 */
		saveRefreshFailed: string
		/**
		 * 暂​时​无​法​关​闭​这​条​消​息​，​请​稍​后​再​试​。
		 */
		messageCloseFailed: string
		/**
		 * 详​情​过​长​，​已​改​为​纯​文​本​发​送​。
		 */
		detailsSentAsText: string
		/**
		 * 暂​时​无​法​更​新​详​情​，​请​稍​后​重​试​。
		 */
		detailsUpdateFailed: string
		/**
		 * 语​音​输​入​失​败​：
		 */
		voiceInputFailedPrefix: string
		/**
		 * 找​不​到​附​件​：
		 */
		attachmentNotFoundPrefix: string
		/**
		 * 以​下​附​件​未​能​完​成​解​析​：​

		 */
		attachmentsParseFailedPrefix: string
	}
	success: {
		/**
		 * 已​请​求​停​止​当​前​操​作​。
		 */
		stopRequested: string
		/**
		 * 已​请​求​停​止​这​个​会​话​的​当​前​操​作​。
		 */
		stopRequestedForSession: string
		/**
		 * 已​切​换​到​会​话​：
		 */
		sessionSwitchedPrefix: string
		/**
		 * 已​保​存​。
		 */
		settingsSaved: string
		/**
		 * 设​置​已​保​存​，​但​消​息​暂​时​无​法​更​新​。
		 */
		settingsSavedButMessageUpdateFailed: string
		/**
		 * 已​恢​复​默​认​，​记​得​保​存​。
		 */
		defaultsRestored: string
		/**
		 * 已​清​空​会​话​「
		 */
		threadClearedPrefix: string
		/**
		 * 」​的​上​下​文​，​并​立​即​切​换​到​新​的​ ​C​o​d​e​x​ ​线​程​。​上​一​线​程​已​保​留​到​归​档​会​话​中​，​可​用​ ​/​s​e​s​s​i​o​n​s​ ​a​r​c​h​i​v​e​d​ ​查​看​。
		 */
		threadClearedSuffix: string
		/**
		 * 已​重​置​会​话​「
		 */
		threadResetPrefix: string
		/**
		 * 」​并​立​即​启​动​新​的​ ​C​o​d​e​x​ ​线​程​。
		 */
		threadResetSuffix: string
		/**
		 * 会​话​标​题​已​更​新​为​：
		 */
		threadNameUpdatedPrefix: string
		/**
		 * 已​为​会​话​「
		 */
		threadMetaUpdatedPrefix: string
		/**
		 * 」​更​新​线​程​元​数​据​：
		 */
		threadMetaUpdatedSuffix: string
		/**
		 * 已​为​会​话​「
		 */
		terminalsCleanedPrefix: string
		/**
		 * 」​清​理​当​前​线​程​的​后​台​终​端​。
		 */
		terminalsCleanedSuffix: string
		/**
		 * 已​为​会​话​「
		 */
		modelSetPrefix: string
		/**
		 * 」​设​置​模​型​：
		 */
		modelSetSuffix: string
		/**
		 * 
	​下​次​任​务​开​始​时​生​效​。
		 */
		modelSetEffect: string
		/**
		 * 已​为​会​话​「
		 */
		planModeToggledPrefix: string
		/**
		 * 」
		 */
		planModeToggledSuffix: string
		/**
		 *  ​P​l​a​n​ ​m​o​d​e​。
		 */
		planModeToggledPlan: string
		/**
		 * 已​创​建​审​查​会​话​：
		 */
		reviewSessionCreatedPrefix: string
		/**
		 * 已​创​建​分​叉​会​话​：
		 */
		forkSessionCreatedPrefix: string
		/**
		 * 已​为​会​话​「
		 */
		compactRequestedPrefix: string
		/**
		 * 」​请​求​压​缩​当​前​线​程​。
		 */
		compactRequestedSuffix: string
		/**
		 * 已​回​滚​到​：
		 */
		rollbackCompletedPrefix: string
		/**
		 * 已​为​会​话​「
		 */
		rollbackTurnsPrefix: string
		/**
		 * 」​回​滚​最​近​ 
		 */
		rollbackTurnsMiddle: string
		/**
		 *  ​个​ ​t​u​r​n​。
		 */
		rollbackTurnsSuffix: string
		/**
		 * 已​回​滚​最​近​ 
		 */
		rollbackTurnsNoSessionPrefix: string
		/**
		 *  ​个​ ​t​u​r​n​。
		 */
		rollbackTurnsNoSessionSuffix: string
		/**
		 * 已​为​项​目​「
		 */
		pluginInstalledPrefix: string
		/**
		 * 」​安​装​插​件​：
		 */
		pluginInstalledMiddle: string
		/**
		 * 已​为​项​目​「
		 */
		pluginUninstalledPrefix: string
		/**
		 * 」​卸​载​插​件​：
		 */
		pluginUninstalledMiddle: string
		/**
		 * 已​重​新​加​载​ ​M​C​P​ ​服​务​器​配​置​。
		 */
		mcpReloaded: string
		/**
		 * 已​生​成​ ​M​C​P​ ​登​录​链​接​：
		 */
		mcpLoginLinkPrefix: string
		/**
		 * 

		 */
		mcpLoginLinkMiddle: string
		/**
		 * 
	​完​成​后​重​新​发​送​ ​/​m​c​p​ ​查​看​最​新​状​态​。
		 */
		mcpLoginLinkSuffix: string
		/**
		 * 已​为​会​话​「
		 */
		planModeTogglePrefix: string
		/**
		 * 」
		 */
		planModeToggleMiddle: string
		/**
		 *  ​P​l​a​n​ ​m​o​d​e​。
		 */
		planModeToggleSuffix: string
		/**
		 * 已​取​消​项​目​别​名​修​改​。
		 */
		renameProjectCancelled: string
		/**
		 * 已​取​消​会​话​重​命​名​。
		 */
		renameSessionCancelled: string
		/**
		 * 已​发​送​图​片​预​览​。
		 */
		imagePreviewSent: string
		/**
		 * 已​取​消​待​发​送​的​结​构​化​输​入​。
		 */
		structuredInputCancelled: string
		/**
		 * 已​收​到​语​音​，
		 */
		voiceReceivedPrefix: string
		/**
		 * 正​在​转​写​。
		 */
		voiceTranscribing: string
		/**
		 * 正​在​排​队​转​写​。​前​方​还​有​ 
		 */
		voiceQueuedPrefix: string
		/**
		 *  ​条​语​音​。
		 */
		voiceQueuedSuffix: string
	}
	hints: {
		/**
		 * 如​需​查​看​或​刷​新​ ​H​u​b​，​可​发​送​ ​/​h​u​b​。
		 */
		hubCommandReminder: string
		/**
		 * 需​要​查​看​运​行​卡​片​时​，​可​发​送​ ​/​h​u​b​。
		 */
		hubCommandReminderShort: string
		/**
		 * 请​先​用​ ​/​n​e​w​ ​选​择​项​目​，​或​用​ ​/​r​e​s​u​m​e​ ​a​l​l​ ​查​看​全​部​ ​C​o​d​e​x​ ​会​话​。
		 */
		selectProjectOrResume: string
		/**
		 * 已​记​录
		 */
		recordedContinueOrCancelPrefix: string
		/**
		 * ，​请​继​续​发​送​任​务​说​明​，​或​发​送​ ​/​c​a​n​c​e​l​ ​取​消​。
		 */
		recordedContinueOrCancelSuffix: string
	}
	prompts: {
		/**
		 * 请​输​入​新​的​项​目​别​名​。​
	​发​送​ ​/​c​a​n​c​e​l​ ​取​消​。
		 */
		renameProject: string
		/**
		 * 请​输​入​新​的​会​话​名​称​。​
	​发​送​ ​/​c​a​n​c​e​l​ ​取​消​。
		 */
		renameSession: string
		/**
		 * 请​继​续​发​送​要​和
		 */
		continueStructuredInputPrefix: string
		/**
		 * 一​起​交​给​ ​C​o​d​e​x​ ​的​说​明​。
		 */
		continueStructuredInputSuffix: string
	}
	labels: {
		/**
		 * [​启​用​]
		 */
		enabled: string
		/**
		 * [​禁​用​]
		 */
		disabled: string
		/**
		 * [​已​安​装​]
		 */
		installed: string
		/**
		 * [​未​安​装​]
		 */
		notInstalled: string
		/**
		 * [​可​访​问​]
		 */
		accessible: string
		/**
		 * [​不​可​访​问​]
		 */
		notAccessible: string
		/**
		 * 可​用​技​能
		 */
		availableSkills: string
		/**
		 * 可​用​插​件
		 */
		availablePlugins: string
		/**
		 * 当​前​可​用​ ​A​p​p​s
		 */
		availableApps: string
		/**
		 * 市​场​：
		 */
		marketplacePrefix: string
		/**
		 * 来​源​插​件​：
		 */
		sourcePluginPrefix: string
		/**
		 * 安​装​地​址​：
		 */
		installUrlPrefix: string
		/**
		 * M​C​P​ ​服​务​器​状​态
		 */
		mcpServerStatus: string
		/**
		 * 工​具​ 
		 */
		mcpToolsPrefix: string
		/**
		 * 资​源​ 
		 */
		mcpResourcesPrefix: string
		/**
		 * 模​板​ 
		 */
		mcpTemplatesPrefix: string
		/**
		 * 当​前​ ​C​o​d​e​x​ ​账​号
		 */
		currentCodexAccount: string
		/**
		 * 账​号​：​未​登​录
		 */
		accountNotLoggedIn: string
		/**
		 * 类​型​：​A​P​I​ ​K​e​y
		 */
		accountTypeApiKey: string
		/**
		 * 类​型​：​C​h​a​t​G​P​T
		 */
		accountTypeChatGPT: string
		/**
		 * 邮​箱​：
		 */
		accountEmailPrefix: string
		/**
		 * 计​划​：
		 */
		accountPlanPrefix: string
		/**
		 * 需​要​ ​O​p​e​n​A​I​ ​A​u​t​h
		 */
		requiresOpenaiAuth: string
		/**
		 * 是
		 */
		requiresOpenaiAuthYes: string
		/**
		 * 否
		 */
		requiresOpenaiAuthNo: string
		/**
		 * 额​度​：
		 */
		rateLimitQuotaPrefix: string
		/**
		 * 限​额​计​划​：
		 */
		rateLimitPlanPrefix: string
		/**
		 *  ​分​钟
		 */
		rateLimitWindowMinutesSuffix: string
		/**
		 * 当​前​窗​口
		 */
		rateLimitWindowCurrent: string
		/**
		 * 主​额​度​使​用​：
		 */
		rateLimitPrimaryUsagePrefix: string
		/**
		 * %​（
		 */
		rateLimitPrimaryUsageMiddle: string
		/**
		 * ）
		 */
		rateLimitPrimaryUsageSuffix: string
		/**
		 * C​r​e​d​i​t​s​：
		 */
		creditsPrefix: string
		/**
		 * C​r​e​d​i​t​s​：​无​限
		 */
		creditsUnlimited: string
		/**
		 * 可​用
		 */
		creditsAvailable: string
		/**
		 * 不​可​用
		 */
		creditsUnavailable: string
		/**
		 * s​k​i​l​l​：
		 */
		skillLabelPrefix: string
		/**
		 * 语​音​：
		 */
		voiceInputPrefix: string
		/**
		 * 图​片​输​入
		 */
		imageInput: string
		/**
		 * 结​构​化​输​入
		 */
		structuredInput: string
		/**
		 * 引​用​：
		 */
		referencePrefix: string
		/**
		 * 本​地​图​片​：
		 */
		localImagePrefix: string
		/**
		 * 附​件​：
		 */
		attachmentPrefix: string
		/**
		 *  ​张​图​片
		 */
		multipleImagesSuffix: string
		/**
		 * 图​片
		 */
		image: string
		/**
		 * 清​空​前​：
		 */
		preClearPrefix: string
		/**
		 * 扫​描​警​告​：
		 */
		scanWarningPrefix: string
		/**
		 * 使​用​ ​/​s​k​i​l​l​ ​<​技​能​名​>​ ​:​:​ ​任​务​说​明​ ​将​ ​s​k​i​l​l​ ​作​为​结​构​化​输​入​发​送​给​ ​C​o​d​e​x​。
		 */
		skillUsage: string
		/**
		 * 使​用​ ​/​p​l​u​g​i​n​ ​i​n​s​t​a​l​l​ ​<​市​场​>​/​<​插​件​名​>​ ​安​装​插​件​。
		 */
		pluginInstallUsage: string
		/**
		 * 使​用​ ​/​p​l​u​g​i​n​ ​u​n​i​n​s​t​a​l​l​ ​<​插​件​I​D​>​ ​卸​载​插​件​。
		 */
		pluginUninstallUsage: string
		/**
		 * 例​如​：​/​p​l​u​g​i​n​ ​i​n​s​t​a​l​l​ 
		 */
		pluginInstallExamplePrefix: string
		/**
		 * 使​用​ ​/​m​c​p​ ​r​e​l​o​a​d​ ​重​新​加​载​配​置​，​或​ ​/​m​c​p​ ​l​o​g​i​n​ ​<​名​称​>​ ​启​动​ ​O​A​u​t​h​ ​登​录​。
		 */
		mcpUsage: string
		/**
		 * 上​一​级
		 */
		parentDirectory: string
		/**
		 * 在​当​前​目​录​新​建
		 */
		createSessionHere: string
		/**
		 * 刷​新
		 */
		refresh: string
		/**
		 * M​C​P​ ​工​具
		 */
		mcpTool: string
		/**
		 * 当​前​会​话​：
		 */
		currentSessionPrefix: string
		/**
		 * 当​前​项​目​：
		 */
		currentProjectPrefix: string
		/**
		 * 开​启
		 */
		planModeOn: string
		/**
		 * 关​闭
		 */
		planModeOff: string
		/**
		 * 当​前​任​务​不​受​影​响​，​下​次​任​务​开​始​时​生​效​。
		 */
		planModeNextTaskEffect: string
		/**
		 * 下​次​任​务​开​始​时​生​效​。
		 */
		planModeNextTaskEffectOnly: string
		/**
		 * 语​音​转​写​：
		 */
		voiceTranscriptionPrefix: string
		/**
		 * 请​逐​字​转​写​收​到​的​语​音​，​只​返​回​转​写​文​本​，​不​要​解​释​。
		 */
		voiceRealtimeTranscriptionPrompt: string
		/**
		 * 已​接​收​文​件​附​件​：​

		 */
		attachmentReceivedSinglePrefix: string
		/**
		 * 
	​下​一​条​消​息​会​自​动​带​上​最​近​附​件​；​也​可​用​ ​/​a​t​t​a​c​h​ ​<​附​件​I​D​>​ ​:​:​ ​任​务​说​明​；​发​送​ ​/​c​a​n​c​e​l​ ​可​取​消​。
		 */
		attachmentReceivedSingleSuffix: string
		/**
		 * 已​接​收​ 
		 */
		attachmentReceivedMultiplePrefix: string
		/**
		 *  ​个​文​件​附​件​：​

		 */
		attachmentReceivedMultipleMiddle: string
		/**
		 * 
	​下​一​条​消​息​会​自​动​带​上​最​近​附​件​；​也​可​用​ ​/​a​t​t​a​c​h​ ​<​附​件​I​D​>​ ​:​:​ ​任​务​说​明​；​发​送​ ​/​c​a​n​c​e​l​ ​可​取​消​。
		 */
		attachmentReceivedMultipleSuffix: string
		/**
		 * 以​下​是​附​件​《
		 */
		attachmentExtractContentPrefix: string
		/**
		 * 》​的​提​取​内​容​：​
	​

		 */
		attachmentExtractContentMiddle: string
		/**
		 * 以​下​是​附​件​《
		 */
		attachmentExtractContentTruncatedPrefix: string
		/**
		 * 》​的​提​取​内​容​（​已​截​断​）​：​
	​

		 */
		attachmentExtractContentTruncatedMiddle: string
	}
	statuses: {
		/**
		 * 已​完​成
		 */
		completed: string
		/**
		 * 失​败
		 */
		failed: string
		/**
		 * 已​中​断
		 */
		interrupted: string
		/**
		 * 空​闲
		 */
		idle: string
		/**
		 * 执​行​中
		 */
		running: string
		/**
		 * 不​支​持​认​证
		 */
		authNotSupported: string
		/**
		 * 未​登​录
		 */
		notLoggedIn: string
		/**
		 * 上​次​运​行​因​桥​重​启​而​停​止
		 */
		stoppedByBridgeRestart: string
	}
	notices: {
		/**
		 * C​o​d​e​x​ ​配​置​警​告​：
		 */
		configWarningPrefix: string
		/**
		 * C​o​d​e​x​ ​弃​用​提​示​：
		 */
		deprecationWarningPrefix: string
		/**
		 * C​o​d​e​x​ ​已​调​整​模​型​：
		 */
		modelAdjustedPrefix: string
		/**
		 *  ​-​>​ 
		 */
		modelAdjustedArrow: string
		/**
		 *  ​(
		 */
		modelAdjustedReasonPrefix: string
		/**
		 * )
		 */
		modelAdjustedReasonSuffix: string
		/**
		 * C​o​d​e​x​ ​技​能​列​表​已​刷​新​。
		 */
		skillsRefreshed: string
		/**
		 * C​o​d​e​x​ ​线​程​上​下​文​已​压​缩​。
		 */
		threadCompacted: string
	}
	help: {
		/**
		 * 用​法​：​/​r​e​v​i​e​w​ ​[​d​e​t​a​c​h​e​d​]​ ​[​b​r​a​n​c​h​ ​<​分​支​>​|​c​o​m​m​i​t​ ​<​S​H​A​>​|​c​u​s​t​o​m​ ​<​说​明​>​]
		 */
		reviewUsage: string
		/**
		 * 用​法​：​/​t​h​r​e​a​d​ ​n​a​m​e​ ​<​名​称​>​ ​或​ ​/​t​h​r​e​a​d​ ​m​e​t​a​ ​b​r​a​n​c​h​=​<​分​支​>​ ​s​h​a​=​<​提​交​>​ ​o​r​i​g​i​n​=​<​U​R​L​>​ ​或​ ​/​t​h​r​e​a​d​ ​c​l​e​a​n​-​t​e​r​m​i​n​a​l​s
		 */
		threadUsage: string
	}
	warnings: {
		/**
		 * 注​意​：​这​不​会​自​动​撤​销​代​理​已​经​写​到​本​地​文​件​的​改​动​。
		 */
		rollbackNoAutoRevert: string
		/**
		 * 这​些​ ​A​p​p​ ​可​能​还​需​要​额​外​授​权​：
		 */
		appsNeedAuthorization: string
		/**
		 * 扫​描​警​告​：
		 */
		scanErrorPrefix: string
	}
	input: {
		/**
		 * 是
		 */
		yes: string
		/**
		 * 否
		 */
		no: string
	}
	feishu: {
		/**
		 * 帮​助
		 */
		help: string
		/**
		 * 新​建​会​话
		 */
		newSession: string
		/**
		 * 当​前​状​态
		 */
		status: string
		/**
		 * 最​近​会​话
		 */
		sessions: string
		/**
		 * 中​断​操​作
		 */
		interrupt: string
		/**
		 * 查​看​详​情
		 */
		inspect: string
		/**
		 * 运​行​卡
		 */
		hub: string
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * 无
		 */
		none: () => LocalizedString
		/**
		 * 是
		 */
		yes: () => LocalizedString
		/**
		 * 否
		 */
		no: () => LocalizedString
		/**
		 * 正常
		 */
		ok: () => LocalizedString
		/**
		 * 异常
		 */
		unhealthy: () => LocalizedString
		/**
		 * 暂无
		 */
		unavailable: () => LocalizedString
		/**
		 * 关闭
		 */
		close: () => LocalizedString
		/**
		 * 返回
		 */
		back: () => LocalizedString
		/**
		 * 当前
		 */
		current: () => LocalizedString
		/**
		 * 空槽位
		 */
		emptySlot: () => LocalizedString
		/**
		 * 默认模型
		 */
		defaultModel: () => LocalizedString
		/**
		 * 默认
		 */
		'default': () => LocalizedString
		/**
		 * 配置
		 */
		configured: () => LocalizedString
		/**
		 * 生效
		 */
		effective: () => LocalizedString
		/**
		 * ；
		 */
		separator: () => LocalizedString
		/**
		 * 其他
		 */
		other: () => LocalizedString
		/**
		 * 上一页
		 */
		previousPage: () => LocalizedString
		/**
		 * 下一页
		 */
		nextPage: () => LocalizedString
		/**
		 * 上一页
		 */
		previous: () => LocalizedString
		/**
		 * 下一页
		 */
		next: () => LocalizedString
		/**
		 * 待处理
		 */
		pending: () => LocalizedString
		/**
		 * 未完成
		 */
		incomplete: () => LocalizedString
		/**
		 * 命令
		 */
		commands: () => LocalizedString
	}
	status: {
		/**
		 * 服务状态
		 */
		title: () => LocalizedString
		/**
		 * 桥接状态：
		 */
		bridgeState: () => LocalizedString
		/**
		 * 平台连通：
		 */
		platformConnectivity: () => LocalizedString
		/**
		 * 配置完成：
		 */
		setupComplete: () => LocalizedString
		/**
		 * Codex 可用：
		 */
		codexAvailable: () => LocalizedString
		/**
		 * 当前会话：
		 */
		currentSession: () => LocalizedString
		/**
		 * 最近检查：
		 */
		lastChecked: () => LocalizedString
		/**
		 * 问题：
		 */
		issues: () => LocalizedString
	}
	where: {
		/**
		 * 当前会话
		 */
		title: () => LocalizedString
		/**
		 * 会话名：
		 */
		sessionName: () => LocalizedString
		/**
		 * 项目：
		 */
		project: () => LocalizedString
		/**
		 * 路径：
		 */
		path: () => LocalizedString
		/**
		 * 状态：
		 */
		state: () => LocalizedString
		/**
		 * 模型配置：
		 */
		modelConfigured: () => LocalizedString
		/**
		 * 模型生效：
		 */
		modelEffective: () => LocalizedString
		/**
		 * Bridge 会话 ID：
		 */
		bridgeSessionId: () => LocalizedString
		/**
		 * Codex 线程 ID：
		 */
		codexThreadId: () => LocalizedString
		/**
		 * 最近 Turn ID：
		 */
		lastTurnId: () => LocalizedString
		/**
		 * 上次结果：
		 */
		lastResult: () => LocalizedString
		/**
		 * 当前没有活动会话。
		 */
		noActiveSession: () => LocalizedString
		/**
		 * 尚未创建（首次发送任务后生成）
		 */
		threadNotCreated: () => LocalizedString
	}
	sessions: {
		/**
		 * 最近会话
		 */
		recentTitle: () => LocalizedString
		/**
		 * 已归档会话
		 */
		archivedTitle: () => LocalizedString
		/**
		 * 已批量归档会话
		 */
		batchArchivedTitle: () => LocalizedString
		/**
		 * 暂无会话。
		 */
		empty: () => LocalizedString
		/**
		 * [当前] 
		 */
		currentMarker: () => LocalizedString
		/**
		 * 暂无会话。
		 */
		resumeEmpty: () => LocalizedString
		/**
		 * 可恢复的 Codex 会话
		 */
		resumeTitle: () => LocalizedString
	}
	sessionState: {
		/**
		 * 执行中
		 */
		running: () => LocalizedString
		/**
		 * 已中断
		 */
		interrupted: () => LocalizedString
		/**
		 * 失败
		 */
		failed: () => LocalizedString
		/**
		 * 空闲
		 */
		idle: () => LocalizedString
		/**
		 * 准备中
		 */
		starting: () => LocalizedString
		/**
		 * 等待中
		 */
		blocked: () => LocalizedString
		/**
		 * 上次已完成
		 */
		lastCompleted: () => LocalizedString
		/**
		 * 上次已中断
		 */
		lastInterrupted: () => LocalizedString
		/**
		 * 上次失败
		 */
		lastFailed: () => LocalizedString
		/**
		 * 桥接服务重启
		 */
		failureBridgeRestart: () => LocalizedString
		/**
		 * Codex 服务断开
		 */
		failureAppServerLost: () => LocalizedString
		/**
		 * 执行失败
		 */
		failureTurnFailed: () => LocalizedString
		/**
		 * 未知原因
		 */
		failureUnknown: () => LocalizedString
		/**
		 * 未知
		 */
		unknown: () => LocalizedString
	}
	projects: {
		/**
		 * 选择要新建会话的项目
		 */
		pickerTitle: () => LocalizedString
		/**
		 * 还没有最近项目，请浏览目录或手动输入路径。
		 */
		empty: () => LocalizedString
		/**
		 * 浏览目录
		 */
		browseDirectory: () => LocalizedString
		/**
		 * 手动输入路径
		 */
		enterPath: () => LocalizedString
		/**
		 * 返回项目列表
		 */
		backToProjects: () => LocalizedString
		/**
		 * 选择要浏览的根目录
		 */
		selectRoot: () => LocalizedString
		/**
		 * 请发送要开始会话的目录路径，例如：/home/ubuntu/Repo/openclaw
	发送 /cancel 返回项目列表。
		 */
		manualPathPrompt: () => LocalizedString
		/**
		 * 要在这个目录中新建会话吗？
		 */
		confirmNewSession: () => LocalizedString
		/**
		 * 确认新建会话
		 */
		confirmNewSessionButton: () => LocalizedString
		/**
		 * 这个入口已下线。请使用浏览目录或手动输入路径。
		 */
		offlineEntry: () => LocalizedString
		/**
		 * 已新建会话
		 */
		newSessionCreated: () => LocalizedString
		/**
		 * 已切换会话
		 */
		sessionSwitched: () => LocalizedString
		/**
		 * 已恢复 Codex 会话
		 */
		codexSessionResumed: () => LocalizedString
		/**
		 * 当前项目：
		 */
		currentProject: () => LocalizedString
		/**
		 * 已归档会话
		 */
		archivedSession: () => LocalizedString
		/**
		 * 已归档：
		 */
		batchArchived: () => LocalizedString
		/**
		 * 已跳过运行中：
		 */
		batchSkippedRunning: () => LocalizedString
		/**
		 * 失败：
		 */
		batchFailed: () => LocalizedString
		/**
		 * 已恢复会话
		 */
		sessionRestored: () => LocalizedString
		/**
		 * 当前会话已重命名为：
		 */
		sessionRenamed: () => LocalizedString
		/**
		 * 当前项目别名已更新为：
		 */
		projectAliasRenamed: () => LocalizedString
		/**
		 * 已清除项目别名：
		 */
		projectAliasCleared: () => LocalizedString
		/**
		 * 已收藏项目：
		 */
		projectFavorited: () => LocalizedString
		/**
		 * 当前没有活动会话，请发送 /new 选择项目。
		 */
		noActiveSession: () => LocalizedString
		/**
		 * 重命名会话
		 */
		renameSession: () => LocalizedString
		/**
		 * 设置项目别名
		 */
		setProjectAlias: () => LocalizedString
		/**
		 * 清除项目别名
		 */
		clearProjectAlias: () => LocalizedString
		groups: {
			/**
			 * 已收藏
			 */
			pinned: () => LocalizedString
			/**
			 * 最近使用
			 */
			recent: () => LocalizedString
		}
		badges: {
			/**
			 * 最近
			 */
			recent: () => LocalizedString
			/**
			 * 本地发现
			 */
			locallyDiscovered: () => LocalizedString
			/**
			 * 有历史会话
			 */
			hasHistory: () => LocalizedString
		}
	}
	model: {
		/**
		 * 选择模型
		 */
		selectModel: () => LocalizedString
		/**
		 * 选择思考强度
		 */
		selectEffort: () => LocalizedString
		/**
		 * 先选模型，再按该模型支持情况选择思考强度。
		 */
		modelTip: () => LocalizedString
		/**
		 * 仅展示这个模型实际支持的档位。
		 */
		effortTip: () => LocalizedString
		/**
		 * 已关闭模型选择
		 */
		modelPickerClosed: () => LocalizedString
		/**
		 * 要修改哪个名称？
		 */
		editWhichName: () => LocalizedString
		/**
		 * 已配置
		 */
		configuredMarker: () => LocalizedString
		/**
		 * 生效
		 */
		effectiveMarker: () => LocalizedString
		/**
		 * 清除模型/强度覆盖
		 */
		clearOverride: () => LocalizedString
		/**
		 * 页
		 */
		pageLabel: () => LocalizedString
		/**
		 * 个
		 */
		countUnit: () => LocalizedString
		/**
		 * 当前
		 */
		current: () => LocalizedString
		/**
		 * 默认
		 */
		defaultAlias: () => LocalizedString
		/**
		 * 默认模型 + 默认
		 */
		defaultSelectionLabel: () => LocalizedString
	}
	commands: {
		/**
		 * 可用指令
		 */
		heading: () => LocalizedString
		groups: {
			/**
			 * 帮助与状态
			 */
			helpStatus: () => LocalizedString
			/**
			 * 会话与项目
			 */
			sessionProject: () => LocalizedString
			/**
			 * Codex
			 */
			codex: () => LocalizedString
			/**
			 * 控制
			 */
			control: () => LocalizedString
		}
	}
	commandPanel: {
		/**
		 * 打开命令面板
		 */
		openPanel: () => LocalizedString
		/**
		 * 快捷指令
		 */
		title: () => LocalizedString
		/**
		 * 点击按钮即可执行桥接指令。
		 */
		tapToRun: () => LocalizedString
		/**
		 * 当前快捷指令：
		 */
		selectedLabel: () => LocalizedString
		/**
		 * 当前还没有已配置的快捷指令。
		 */
		noCommands: () => LocalizedString
		/**
		 * 完整帮助
		 */
		fullHelp: () => LocalizedString
		/**
		 * 编辑快捷指令
		 */
		editCommands: () => LocalizedString
		/**
		 * 编辑快捷指令
		 */
		editTitle: () => LocalizedString
		/**
		 * 点击按钮进行选择或移除。选择顺序就是显示顺序。
		 */
		editHint: () => LocalizedString
		/**
		 * 新选中的指令会追加到末尾。
		 */
		editAppendHint: () => LocalizedString
		/**
		 * 当前分组：
		 */
		currentGroup: () => LocalizedString
		/**
		 * 已选指令：
		 */
		selectedCommands: () => LocalizedString
		/**
		 * 当前还没有选中的快捷指令。
		 */
		noSelected: () => LocalizedString
		/**
		 * 分组页码：
		 */
		groupPage: () => LocalizedString
		/**
		 * 总页码：
		 */
		totalPage: () => LocalizedString
		/**
		 * 保存
		 */
		save: () => LocalizedString
		/**
		 * 恢复默认
		 */
		restoreDefault: () => LocalizedString
	}
	browser: {
		/**
		 * 文件浏览
		 */
		title: () => LocalizedString
		/**
		 * 当前项目：
		 */
		project: () => LocalizedString
		/**
		 * 当前位置：
		 */
		location: () => LocalizedString
		/**
		 * 页码：
		 */
		page: () => LocalizedString
		/**
		 * 模式：
		 */
		mode: () => LocalizedString
		/**
		 * 只读浏览
		 */
		readonly: () => LocalizedString
		/**
		 * 项目根
		 */
		root: () => LocalizedString
		/**
		 * 当前目录为空。
		 */
		empty: () => LocalizedString
		/**
		 * 上一级
		 */
		up: () => LocalizedString
		/**
		 * 回到项目根
		 */
		backToRoot: () => LocalizedString
		/**
		 * 刷新
		 */
		refresh: () => LocalizedString
		/**
		 * 在当前目录新建会话
		 */
		useCurrentDirectory: () => LocalizedString
		/**
		 * 文件预览
		 */
		previewTitle: () => LocalizedString
		/**
		 * 文件：
		 */
		file: () => LocalizedString
		/**
		 * 路径：
		 */
		path: () => LocalizedString
		/**
		 * 大小：
		 */
		size: () => LocalizedString
		/**
		 * 修改时间：
		 */
		modified: () => LocalizedString
		/**
		 * 预览页：
		 */
		previewPage: () => LocalizedString
		/**
		 * 仅预览前 48 KB。
		 */
		previewTruncated: () => LocalizedString
		/**
		 * 返回目录
		 */
		returnToDirectory: () => LocalizedString
		/**
		 * 文件信息
		 */
		infoTitle: () => LocalizedString
		/**
		 * 类型：
		 */
		type: () => LocalizedString
		/**
		 * 二进制或暂不支持预览
		 */
		binary: () => LocalizedString
		/**
		 * 图片预览
		 */
		imagePreview: () => LocalizedString
		/**
		 * 确认新建会话
		 */
		confirmNewSession: () => LocalizedString
		/**
		 * 目录：
		 */
		directory: () => LocalizedString
		/**
		 * 显示名：
		 */
		displayName: () => LocalizedString
		/**
		 * 要在这个目录新建会话吗？
		 */
		confirmNewInDirectory: () => LocalizedString
		/**
		 * 返回目录
		 */
		backToDirectory: () => LocalizedString
	}
	finalAnswer: {
		/**
		 * 展开全文
		 */
		expandFull: () => LocalizedString
		/**
		 * 收起
		 */
		collapse: () => LocalizedString
		/**
		 * 实施这个计划
		 */
		implementPlan: () => LocalizedString
		/**
		 * 最近输出
		 */
		recentOutput: () => LocalizedString
		/**
		 * 点击「展开最近输出」查看该会话最近一次输出。
		 */
		expandRecentOutputHint: () => LocalizedString
		/**
		 * 该会话还没有最近输出。
		 */
		noRecentOutput: () => LocalizedString
		/**
		 * 展开最近输出
		 */
		expandRecentOutput: () => LocalizedString
		/**
		 * 收起最近输出
		 */
		collapseRecentOutput: () => LocalizedString
		/**
		 * 展开方案
		 */
		expandPlan: () => LocalizedString
		/**
		 * 收起方案
		 */
		collapsePlan: () => LocalizedString
		/**
		 * 已开始实施。
		 */
		planConsumed: () => LocalizedString
		/**
		 * 最终答复暂未送达。点击“展开全文”重新渲染。
		 */
		finalAnswerDeferred: () => LocalizedString
		/**
		 * 方案结果暂未送达。点击“展开方案”重新渲染。
		 */
		planResultDeferred: () => LocalizedString
		/**
		 * 已折叠，共 
		 */
		collapsedMultiPagePrefix: () => LocalizedString
		/**
		 *  页，点击
		 */
		collapsedMultiPageMiddle: () => LocalizedString
		/**
		 * 查看。
		 */
		collapsedMultiPageSuffix: () => LocalizedString
		/**
		 * 已折叠，点击
		 */
		collapsedSinglePrefix: () => LocalizedString
		/**
		 * 查看剩余内容。
		 */
		collapsedSingleSuffix: () => LocalizedString
		/**
		 * 第 
		 */
		pagePrefix: () => LocalizedString
		/**
		 *  页
		 */
		pageSuffix: () => LocalizedString
	}
	shared: {
		/**
		 * 刚刚
		 */
		justNow: () => LocalizedString
		/**
		 * 分钟前
		 */
		minutesAgo: () => LocalizedString
		/**
		 * 小时前
		 */
		hoursAgo: () => LocalizedString
		/**
		 * 天前
		 */
		daysAgo: () => LocalizedString
		/**
		 * 关闭
		 */
		effortNone: () => LocalizedString
		/**
		 * 极省
		 */
		effortMinimal: () => LocalizedString
		/**
		 * 低
		 */
		effortLow: () => LocalizedString
		/**
		 * 中
		 */
		effortMedium: () => LocalizedString
		/**
		 * 高
		 */
		effortHigh: () => LocalizedString
		/**
		 * 极高
		 */
		effortXhigh: () => LocalizedString
	}
	runtime: {
		/**
		 * 运行状态
		 */
		statusTitle: () => LocalizedString
		/**
		 * 状态
		 */
		state: () => LocalizedString
		/**
		 * 进度
		 */
		progress: () => LocalizedString
		/**
		 * 会话
		 */
		session: () => LocalizedString
		/**
		 * 收起计划清单
		 */
		hidePlan: () => LocalizedString
		/**
		 * 收起 Agent
		 */
		hideAgents: () => LocalizedString
		/**
		 * 计划清单:
		 */
		planLabel: () => LocalizedString
		/**
		 * Agent:
		 */
		agentsLabel: () => LocalizedString
		/**
		 * 计划详情
		 */
		planDetails: () => LocalizedString
		/**
		 * 协作 Agent
		 */
		collabAgents: () => LocalizedString
		/**
		 * 查看中
		 */
		viewing: () => LocalizedString
		/**
		 * 当前输入
		 */
		currentInput: () => LocalizedString
		/**
		 * 当前
		 */
		current: () => LocalizedString
		/**
		 * 查看详情
		 */
		inspect: () => LocalizedString
		/**
		 * 命令
		 */
		commands: () => LocalizedString
		/**
		 * 中断操作
		 */
		interrupt: () => LocalizedString
		/**
		 * 当前查看中的会话
		 */
		currentViewedSession: () => LocalizedString
		/**
		 * 其他运行中的会话
		 */
		otherRunningSessions: () => LocalizedString
		/**
		 * 最近结束的会话
		 */
		recentEndedSessions: () => LocalizedString
		/**
		 * 当前输入会话
		 */
		currentInputSession: () => LocalizedString
		/**
		 * 当前查看中的运行会话
		 */
		focusedRunningSession: () => LocalizedString
		/**
		 * 当前查看中的会话
		 */
		focusedSession: () => LocalizedString
		/**
		 * 其他会话
		 */
		otherSessions: () => LocalizedString
		/**
		 * 最近结束的会话
		 */
		recentTerminalSessions: () => LocalizedString
		/**
		 * 💡 提示：需要查看运行卡片时，可发送 /hub。
		 */
		hubTip: () => LocalizedString
		/**
		 * 💡 提示：使用 /inspect 查看详情，使用 /interrupt 打断，使用 /status 查看状态。
		 */
		surfaceFooter: () => LocalizedString
		/**
		 * 💡 /status | /inspect | /interrupt
		 */
		hubFooter: () => LocalizedString
		/**
		 * 确认中断
		 */
		confirmInterruptTitle: () => LocalizedString
		/**
		 * 要停止当前正在运行的操作吗？
		 */
		confirmInterruptText: () => LocalizedString
		/**
		 * 计划清单
		 */
		planEntry: () => LocalizedString
		fields: {
			/**
			 * 模型名
			 */
			modelName: () => LocalizedString
			/**
			 * 模型 + 推理强度
			 */
			modelWithReasoning: () => LocalizedString
			/**
			 * 当前目录
			 */
			currentDir: () => LocalizedString
			/**
			 * 项目根目录
			 */
			projectRoot: () => LocalizedString
			/**
			 * Git 分支
			 */
			gitBranch: () => LocalizedString
			/**
			 * 剩余上下文
			 */
			contextRemaining: () => LocalizedString
			/**
			 * 已用上下文
			 */
			contextUsed: () => LocalizedString
			/**
			 * 5 小时额度
			 */
			fiveHourLimit: () => LocalizedString
			/**
			 * 周额度
			 */
			weeklyLimit: () => LocalizedString
			/**
			 * Codex 版本
			 */
			codexVersion: () => LocalizedString
			/**
			 * 上下文窗口大小
			 */
			contextWindowSize: () => LocalizedString
			/**
			 * 已用 Token
			 */
			usedTokens: () => LocalizedString
			/**
			 * 累计输入 Token
			 */
			totalInputTokens: () => LocalizedString
			/**
			 * 累计输出 Token
			 */
			totalOutputTokens: () => LocalizedString
			/**
			 * 会话 ID
			 */
			sessionId: () => LocalizedString
			/**
			 * 会话名
			 */
			sessionName: () => LocalizedString
			/**
			 * 项目名
			 */
			projectName: () => LocalizedString
			/**
			 * 项目路径（旧）
			 */
			projectPath: () => LocalizedString
			/**
			 * Plan mode
			 */
			planMode: () => LocalizedString
			/**
			 * 模型 + 强度（旧）
			 */
			modelReasoning: () => LocalizedString
			/**
			 * 线程 ID（旧）
			 */
			threadId: () => LocalizedString
			/**
			 * Turn ID
			 */
			turnId: () => LocalizedString
			/**
			 * 阻塞原因
			 */
			blockedReason: () => LocalizedString
			/**
			 * 当前步骤
			 */
			currentStep: () => LocalizedString
			/**
			 * 本次 Token
			 */
			lastTokenUsage: () => LocalizedString
			/**
			 * 累计 Token
			 */
			totalTokenUsage: () => LocalizedString
			/**
			 * 上下文窗口
			 */
			contextWindow: () => LocalizedString
			/**
			 * 最终答复已就绪
			 */
			finalAnswerReady: () => LocalizedString
		}
		preferences: {
			/**
			 * 已应用 Runtime 卡片字段
			 */
			appliedTitle: () => LocalizedString
			/**
			 * 当前字段：
			 */
			currentFields: () => LocalizedString
			/**
			 * 已关闭 Runtime 卡片字段选择
			 */
			closedTitle: () => LocalizedString
			/**
			 * Runtime 卡片字段
			 */
			title: () => LocalizedString
			/**
			 * 按按钮选择要显示的字段。
			 */
			hint: () => LocalizedString
			/**
			 * 选择顺序就是显示顺序；新选中的字段会追加到末尾。
			 */
			orderHint: () => LocalizedString
			/**
			 * 当前分组：
			 */
			currentGroup: () => LocalizedString
			/**
			 * 已选字段：
			 */
			selectedFields: () => LocalizedString
			/**
			 * 当前没有已选字段。
			 */
			noSelectedFields: () => LocalizedString
			/**
			 * 分组页码：
			 */
			groupPage: () => LocalizedString
			/**
			 * 总页码：
			 */
			totalPage: () => LocalizedString
			/**
			 * 保存并应用
			 */
			save: () => LocalizedString
			/**
			 * 恢复默认
			 */
			reset: () => LocalizedString
		}
		planStatus: {
			/**
			 * 进行中
			 */
			inProgress: () => LocalizedString
			/**
			 * 已完成
			 */
			completed: () => LocalizedString
			/**
			 * 待处理
			 */
			pending: () => LocalizedString
			/**
			 * 失败
			 */
			failed: () => LocalizedString
			/**
			 * 阻塞中
			 */
			blocked: () => LocalizedString
		}
		agentStatus: {
			/**
			 * 等待初始化
			 */
			pendingInit: () => LocalizedString
			/**
			 * 运行中
			 */
			running: () => LocalizedString
			/**
			 * 已完成
			 */
			completed: () => LocalizedString
			/**
			 * 异常
			 */
			errored: () => LocalizedString
			/**
			 * 已停止
			 */
			stopped: () => LocalizedString
			/**
			 * 未找到
			 */
			notFound: () => LocalizedString
			/**
			 * 等待状态更新
			 */
			waitingForUpdate: () => LocalizedString
		}
		interactionState: {
			/**
			 * 待处理
			 */
			pending: () => LocalizedString
			/**
			 * 等待文字回答
			 */
			awaitingText: () => LocalizedString
			/**
			 * 已处理
			 */
			answered: () => LocalizedString
			/**
			 * 已取消
			 */
			canceled: () => LocalizedString
			/**
			 * 已过期
			 */
			expired: () => LocalizedString
			/**
			 * 处理失败
			 */
			failed: () => LocalizedString
		}
		interaction: {
			/**
			 * 类型：
			 */
			type: () => LocalizedString
			/**
			 * 内容：
			 */
			body: () => LocalizedString
			/**
			 * 说明：
			 */
			detail: () => LocalizedString
			/**
			 * 取消本次交互
			 */
			cancelInteraction: () => LocalizedString
			/**
			 * 问题：
			 */
			questionLabel: () => LocalizedString
			/**
			 * 标题：
			 */
			headerLabel: () => LocalizedString
			/**
			 * 这条回答会按敏感输入处理，不会进入可见摘要。
			 */
			secretNotice: () => LocalizedString
			/**
			 * 当前正在等待你直接发送这条问题的文字回答。
			 */
			awaitingTextNotice: () => LocalizedString
			/**
			 * 点击下方按钮后，直接在聊天里发送你的回答。
			 */
			sendTextPrompt: () => LocalizedString
			/**
			 * 发送文字回答
			 */
			sendTextAnswer: () => LocalizedString
			/**
			 * 状态：
			 */
			stateLabel: () => LocalizedString
			/**
			 * 结果：
			 */
			resultLabel: () => LocalizedString
			/**
			 * 已提交回答
			 */
			submittedAnswers: () => LocalizedString
			/**
			 * 收起已提交回答
			 */
			collapseAnswers: () => LocalizedString
			/**
			 * 查看已提交回答
			 */
			expandAnswers: () => LocalizedString
			/**
			 * 已过期
			 */
			expiredLabel: () => LocalizedString
		}
		inspectSection: {
			/**
			 * 详情已折叠，点击按钮展开。
			 */
			collapseHint: () => LocalizedString
			/**
			 * 展开详情
			 */
			expandDetails: () => LocalizedString
			/**
			 * 收起详情
			 */
			collapseDetails: () => LocalizedString
			/**
			 * 详情页：
			 */
			detailPage: () => LocalizedString
			/**
			 * 当前任务详情
			 */
			currentTaskDetails: () => LocalizedString
			/**
			 * 会话：
			 */
			session: () => LocalizedString
			/**
			 * 项目：
			 */
			project: () => LocalizedString
			/**
			 * 状态：
			 */
			state: () => LocalizedString
			/**
			 * 阻塞原因：
			 */
			blockedReason: () => LocalizedString
			/**
			 * 当前动作：
			 */
			currentAction: () => LocalizedString
			/**
			 * 已耗时：
			 */
			elapsedTime: () => LocalizedString
			/**
			 * 最近结论：
			 */
			recentConclusion: () => LocalizedString
			/**
			 * 最终答复：
			 */
			finalAnswerReady: () => LocalizedString
			/**
			 * 已就绪
			 */
			ready: () => LocalizedString
			/**
			 * 说明：
			 */
			note: () => LocalizedString
			/**
			 * 最近动作
			 */
			recentActions: () => LocalizedString
			/**
			 * 最近命令
			 */
			recentCommands: () => LocalizedString
			/**
			 * 最近文件变更
			 */
			recentFileChanges: () => LocalizedString
			/**
			 * 最近工具与搜索
			 */
			recentToolsAndSearch: () => LocalizedString
			/**
			 * 最近 Hook
			 */
			recentHooks: () => LocalizedString
			/**
			 * 提示与告警
			 */
			noticesAndWarnings: () => LocalizedString
			/**
			 * Token 用量
			 */
			tokenUsage: () => LocalizedString
			/**
			 * 最近差异
			 */
			recentDiff: () => LocalizedString
			/**
			 * 计划清单
			 */
			planList: () => LocalizedString
			/**
			 * 方案草稿
			 */
			planDraft: () => LocalizedString
			/**
			 * 补充说明
			 */
			supplementaryNotes: () => LocalizedString
			/**
			 * 待处理交互
			 */
			pendingInteractions: () => LocalizedString
			/**
			 * 最近已答交互
			 */
			recentAnsweredInteractions: () => LocalizedString
			/**
			 * 命令：
			 */
			commandLabel: () => LocalizedString
			/**
			 * 状态：
			 */
			commandState: () => LocalizedString
			/**
			 * 结果：
			 */
			commandResult: () => LocalizedString
			/**
			 * 目录：
			 */
			commandDirectory: () => LocalizedString
			/**
			 * 退出码：
			 */
			commandExitCode: () => LocalizedString
			/**
			 * 耗时：
			 */
			commandDuration: () => LocalizedString
			/**
			 * ，等待文字回答
			 */
			awaitingTextSuffix: () => LocalizedString
			/**
			 * 开始执行
			 */
			turnStarted: () => LocalizedString
			/**
			 * 执行结束（
			 */
			turnCompleted: () => LocalizedString
			/**
			 * 线程阻塞（
			 */
			threadBlocked: () => LocalizedString
			/**
			 * 线程状态：
			 */
			threadStatus: () => LocalizedString
			/**
			 * 开始：
			 */
			itemStarted: () => LocalizedString
			/**
			 * 完成：
			 */
			itemCompleted: () => LocalizedString
		}
		rollback: {
			/**
			 * 选择回滚目标
			 */
			selectTarget: () => LocalizedString
			/**
			 * 只展示用户输入，不展示 agent 输出。
			 */
			onlyUserInput: () => LocalizedString
			/**
			 * 页码：
			 */
			pageLabel: () => LocalizedString
			/**
			 * 确认回滚
			 */
			confirmRollback: () => LocalizedString
			/**
			 * 目标：
			 */
			targetLabel: () => LocalizedString
			/**
			 * 将删除的 turn 数：
			 */
			turnCountToDelete: () => LocalizedString
			/**
			 * 本地文件改动不会自动撤销。
			 */
			localChangesWarning: () => LocalizedString
			/**
			 * 确认回滚
			 */
			confirmButton: () => LocalizedString
			/**
			 * 返回列表
			 */
			backToList: () => LocalizedString
			/**
			 * 已关闭回滚目标选择
			 */
			closedTitle: () => LocalizedString
			/**
			 * 未执行回滚。
			 */
			notRolledBack: () => LocalizedString
			/**
			 * 已关闭活动详情
			 */
			closedInspectTitle: () => LocalizedString
			/**
			 * 重新发送 /inspect 可再次打开。
			 */
			reopenHint: () => LocalizedString
		}
		currentStep: {
			/**
			 * 等待批准
			 */
			waitingForApproval: () => LocalizedString
			/**
			 * 等待输入
			 */
			waitingForInput: () => LocalizedString
			/**
			 * 正在更新计划
			 */
			updatingPlan: () => LocalizedString
			/**
			 * 正在运行命令
			 */
			runningCommand: () => LocalizedString
			/**
			 * 正在修改文件
			 */
			editingFiles: () => LocalizedString
			/**
			 * 正在调用 MCP 工具
			 */
			callingMcpTool: () => LocalizedString
			/**
			 * 正在进行网页搜索
			 */
			webSearch: () => LocalizedString
			/**
			 * 正在整理回复
			 */
			draftingResponse: () => LocalizedString
			/**
			 * 正在思考
			 */
			thinking: () => LocalizedString
			/**
			 * 正在处理任务
			 */
			processingTask: () => LocalizedString
			/**
			 * 等待第一条活动
			 */
			waitingForFirstActivity: () => LocalizedString
			/**
			 * 正在处理中
			 */
			processing: () => LocalizedString
			/**
			 * 等待继续
			 */
			waitingToContinue: () => LocalizedString
			/**
			 * 当前没有进行中的步骤
			 */
			noActiveStep: () => LocalizedString
			/**
			 * 已中断，没有进行中的步骤
			 */
			interruptedNoStep: () => LocalizedString
			/**
			 * 执行失败，没有进行中的步骤
			 */
			failedNoStep: () => LocalizedString
			/**
			 * 等待活动
			 */
			waitingForActivity: () => LocalizedString
		}
		milestone: {
			/**
			 * 最终答复已生成
			 */
			replyGenerated: () => LocalizedString
		}
		threadStatus: {
			/**
			 * 未加载
			 */
			notLoaded: () => LocalizedString
			/**
			 * 空闲
			 */
			idle: () => LocalizedString
			/**
			 * 活跃
			 */
			active: () => LocalizedString
			/**
			 * 系统错误
			 */
			systemError: () => LocalizedString
		}
		blockedToken: {
			/**
			 * 等待批准
			 */
			waitingOnApproval: () => LocalizedString
			/**
			 * 等待输入
			 */
			waitingOnUserInput: () => LocalizedString
		}
		commandState: {
			/**
			 * 进行中
			 */
			running: () => LocalizedString
			/**
			 * 已完成
			 */
			completed: () => LocalizedString
			/**
			 * 失败
			 */
			failed: () => LocalizedString
			/**
			 * 已中断
			 */
			interrupted: () => LocalizedString
		}
		optionalLabel: {
			/**
			 * 模型
			 */
			model: () => LocalizedString
			/**
			 * 目录
			 */
			currentDir: () => LocalizedString
		}
		/**
		 * ... 还有 
		 */
		moreStepsPrefix: () => LocalizedString
		/**
		 *  个步骤
		 */
		moreStepsSuffix: () => LocalizedString
		/**
		 * ... 还有 
		 */
		moreAgentsPrefix: () => LocalizedString
		/**
		 *  个 Agent
		 */
		moreAgentsSuffix: () => LocalizedString
		/**
		 * ... 还有 
		 */
		morePlanItemsPrefix: () => LocalizedString
		/**
		 *  项计划
		 */
		morePlanItemsSuffix: () => LocalizedString
		/**
		 * ... 还有 
		 */
		moreSessionsPrefix: () => LocalizedString
		/**
		 *  个会话未显示
		 */
		moreSessionsSuffix: () => LocalizedString
		/**
		 *  个运行中
		 */
		agentsRunningSuffix: () => LocalizedString
		/**
		 *  个
		 */
		selectedFieldCountSuffix: () => LocalizedString
		/**
		 * 本次：
		 */
		tokenUsageThisPrefix: () => LocalizedString
		/**
		 * 累计：
		 */
		tokenUsageTotalPrefix: () => LocalizedString
		/**
		 * 输入 
		 */
		tokenUsageInput: () => LocalizedString
		/**
		 * ，输出 
		 */
		tokenUsageOutput: () => LocalizedString
		/**
		 * ，缓存 
		 */
		tokenUsageCache: () => LocalizedString
		/**
		 * ，推理 
		 */
		tokenUsageReasoning: () => LocalizedString
		/**
		 * 上下文窗口：
		 */
		tokenContextWindowPrefix: () => LocalizedString
		inspectTurnStatus: {
			/**
			 * 空闲
			 */
			idle: () => LocalizedString
			/**
			 * 准备中
			 */
			starting: () => LocalizedString
			/**
			 * 执行中
			 */
			running: () => LocalizedString
			/**
			 * 等待中
			 */
			blocked: () => LocalizedString
			/**
			 * 已中断
			 */
			interrupted: () => LocalizedString
			/**
			 * 已完成
			 */
			completed: () => LocalizedString
			/**
			 * 失败
			 */
			failed: () => LocalizedString
			/**
			 * 未知
			 */
			unknown: () => LocalizedString
		}
	}
	errors: {
		/**
		 * 这个按钮已过期，请重新操作。
		 */
		buttonExpired: () => LocalizedString
		/**
		 * 当前正在等待你处理交互卡片，请先在卡片中回答或取消。
		 */
		pendingInteractionBlockNotice: () => LocalizedString
		/**
		 * 当前没有活动会话。
		 */
		noActiveSession: () => LocalizedString
		/**
		 * 当前项目仍在执行，请先等待完成或停止当前操作。
		 */
		projectBusy: () => LocalizedString
		/**
		 * 这个交互已过期。
		 */
		interactionExpired: () => LocalizedString
		/**
		 * 这个操作已处理。
		 */
		operationHandled: () => LocalizedString
		/**
		 * Codex 服务暂时不可用，请稍后重试。
		 */
		codexUnavailable: () => LocalizedString
		/**
		 * 这个按钮已过期，请重新发送 /runtime。
		 */
		buttonExpiredRuntime: () => LocalizedString
		/**
		 * 当前项目仍在执行，请等待完成或发送 /interrupt。
		 */
		projectBusyInterrupt: () => LocalizedString
		/**
		 * 找不到这个会话。
		 */
		sessionNotFound: () => LocalizedString
		/**
		 * 暂时无法处理这个交互，请稍后再试。
		 */
		interactionTemporarilyUnavailable: () => LocalizedString
		/**
		 * 暂时无法读取这张图片，请稍后重试。
		 */
		imageReadFailed: () => LocalizedString
		/**
		 * 当前平台正在限流，请稍后再试。
		 */
		platformRateLimited: () => LocalizedString
		/**
		 * 当前没有正在执行的操作。
		 */
		noRunningOperation: () => LocalizedString
		/**
		 * 暂时无法更新这条消息，请稍后再试。
		 */
		messageUpdateFailed: () => LocalizedString
		/**
		 * 请先发送 /new 选择项目。
		 */
		selectProjectFirst: () => LocalizedString
		/**
		 * 这个按钮已过期，请重新发送 /rollback。
		 */
		buttonExpiredRollback: () => LocalizedString
		/**
		 * 这个模型列表已过期，请重新发送 /model。
		 */
		modelListExpired: () => LocalizedString
		/**
		 * 找不到这个模型，请先发送 /model 用按钮选择。
		 */
		modelNotFound: () => LocalizedString
		/**
		 * 当前最多只能并行运行 
		 */
		runningCapacityLimitPrefix: () => LocalizedString
		/**
		 *  个会话，请先等待完成或停止部分任务。
		 */
		runningCapacityLimitSuffix: () => LocalizedString
		/**
		 * 找不到这个技能，请先发送 /skills 查看当前项目的技能列表。
		 */
		skillNotFound: () => LocalizedString
		/**
		 * 找不到这个插件，请先发送 /plugins 查看当前可用列表。
		 */
		pluginNotFound: () => LocalizedString
		/**
		 * 当前项目没有可列出的技能。
		 */
		noSkillsAvailable: () => LocalizedString
		/**
		 * 当前项目没有可列出的插件。
		 */
		noPluginsAvailable: () => LocalizedString
		/**
		 * 当前没有可列出的 Apps。
		 */
		noAppsAvailable: () => LocalizedString
		/**
		 * 当前没有可列出的 MCP 服务器。
		 */
		noMcpServers: () => LocalizedString
		/**
		 * 当前无法生成这个 MCP 服务器的登录链接。
		 */
		mcpLoginFailed: () => LocalizedString
		/**
		 * 当前没有可选择的回滚目标。
		 */
		noRollbackTarget: () => LocalizedString
		/**
		 * 这个回滚目标已失效，请重新发送 /rollback。
		 */
		rollbackTargetExpired: () => LocalizedString
		/**
		 * 当前会话还没有可压缩的 Codex 线程。
		 */
		noThreadToCompact: () => LocalizedString
		/**
		 * 当前会话还没有可分叉的 Codex 线程，请先完成一次任务。
		 */
		noThreadToFork: () => LocalizedString
		/**
		 * 当前会话还没有 Codex 线程，请先完成一次任务。
		 */
		noThreadYet: () => LocalizedString
		/**
		 * 当前会话还没有可回滚的 Codex 线程。
		 */
		noThreadToRollback: () => LocalizedString
		/**
		 * 当前没有可归档会话。
		 */
		noArchivableSessions: () => LocalizedString
		/**
		 * 当前无法归档这个会话，请稍后重试。
		 */
		archiveTemporarilyUnavailable: () => LocalizedString
		/**
		 * 当前无法恢复这个会话，请稍后重试。
		 */
		resumeTemporarilyUnavailable: () => LocalizedString
		/**
		 * 当前最多只能并行运行 
		 */
		runningSessionLimitPrefix: () => LocalizedString
		/**
		 *  个会话，请先等待完成或停止部分任务。
		 */
		runningSessionLimitSuffix: () => LocalizedString
		/**
		 * 当前项目还没有设置别名。
		 */
		noProjectAlias: () => LocalizedString
		/**
		 * 这个项目已经收藏。
		 */
		projectAlreadyStarred: () => LocalizedString
		/**
		 * 当前没有可取消的输入。
		 */
		noCancellableInput: () => LocalizedString
		/**
		 * 当前没有可用的活动详情。
		 */
		noActiveDetails: () => LocalizedString
		/**
		 * 这个 Codex 会话已绑定到另一个聊天。
		 */
		sessionBoundToAnotherChat: () => LocalizedString
		/**
		 * 当前没有可浏览的根目录。
		 */
		noBrowsableRoot: () => LocalizedString
		/**
		 * 这个目录不可用，请重新发送目录路径。
	也可以发送 /cancel 返回项目列表。
		 */
		directoryUnavailable: () => LocalizedString
		/**
		 * 桥接状态未知，请在本机运行 ctb doctor。
		 */
		bridgeStateUnknown: () => LocalizedString
		/**
		 * 找不到这个 Codex 会话。
		 */
		codexSessionNotFound: () => LocalizedString
		/**
		 * 只支持 /archive 或 /archive all。
		 */
		archiveOnlyOrAll: () => LocalizedString
		/**
		 * 暂时无法关闭这条消息，请稍后再试。
		 */
		closeMessageFailed: () => LocalizedString
		/**
		 * 状态存储当前不可用。
		 */
		stateStoreUnavailable: () => LocalizedString
		/**
		 * 暂时无法打开命令面板，请稍后重试。
		 */
		commandPanelOpenFailed: () => LocalizedString
		/**
		 * 暂时无法打开编辑器，请稍后重试。
		 */
		editorOpenFailed: () => LocalizedString
		/**
		 * 暂时无法更新编辑器，请稍后重试。
		 */
		editorUpdateFailed: () => LocalizedString
		/**
		 * 暂时无法关闭编辑器，请稍后重试。
		 */
		editorCloseFailed: () => LocalizedString
		/**
		 * 这个指令当前不能加入快捷指令。
		 */
		commandNotAddable: () => LocalizedString
		/**
		 * 最多只能保留 8 个快捷指令。
		 */
		commandShortcutLimit: () => LocalizedString
		/**
		 * 至少保留 1 个快捷指令。
		 */
		commandShortcutMinimum: () => LocalizedString
		/**
		 * 这个入口已下线。请直接告诉 Codex 发送图片。
		 */
		offlineEntryImage: () => LocalizedString
		/**
		 * 这个入口已下线。请直接告诉 Codex 发送文件。
		 */
		offlineEntryFile: () => LocalizedString
		/**
		 * 当前没有运行中的会话。
		 */
		noRunningSessions: () => LocalizedString
		/**
		 * 当前有待处理的交互，请先完成当前操作。
		 */
		pendingInteractionExists: () => LocalizedString
		/**
		 * 当前无法中断正在运行的操作。
		 */
		interruptUnavailable: () => LocalizedString
		/**
		 * 当前无法中断这个会话的操作。
		 */
		interruptUnavailableForSession: () => LocalizedString
		/**
		 * 这次操作未成功完成，请重试。
		 */
		operationIncomplete: () => LocalizedString
		/**
		 * 本次操作已完成，但没有可返回的最终答复。
		 */
		noFinalResponse: () => LocalizedString
		/**
		 * 这个本地图片路径不可用，请确认文件存在且是常见图片格式。
		 */
		localImageInvalid: () => LocalizedString
		/**
		 * 当前无法把附件 
		 */
		attachmentConversionFailedPrefix: () => LocalizedString
		/**
		 *  转成 Codex 可读输入。
		 */
		attachmentConversionFailedSuffix: () => LocalizedString
		/**
		 * 最近附件暂时无法自动转成 Codex 可读输入，请改用支持文本提取的文件，或稍后再试。
		 */
		attachmentAutoConversionFailed: () => LocalizedString
		/**
		 * 未启用语音输入。
		 */
		voiceNotEnabled: () => LocalizedString
		/**
		 * 暂时无法读取这段语音，请稍后重试。
		 */
		voiceReadFailed: () => LocalizedString
		/**
		 * 暂时无法处理这段语音，请稍后重试。
		 */
		voiceProcessingFailed: () => LocalizedString
		/**
		 * 这条语音对应的会话已不可用，请重新选择会话后再试。
		 */
		voiceSessionUnavailable: () => LocalizedString
		/**
		 * 语音已转写，但对应会话已不可用，请重新发送。
		 */
		voiceTranscribedSessionUnavailable: () => LocalizedString
		/**
		 * OpenAI 语音转写失败，正在尝试 realtime 兜底。
		 */
		voiceTranscriptionFailedRealtimeFallback: () => LocalizedString
		/**
		 * 当前 Codex 模型不支持 realtime 音频输入。
		 */
		realtimeAudioNotSupported: () => LocalizedString
		/**
		 * 系统里找不到 ffmpeg：
		 */
		ffmpegNotFoundPrefix: () => LocalizedString
		/**
		 * 当前会话已经变化，请重新发送结构化输入。
		 */
		sessionChanged: () => LocalizedString
		/**
		 * 用法：/skill <技能名> :: 任务说明
		 */
		skillUsageHint: () => LocalizedString
		/**
		 * 用法：/plugin install <市场>/<插件名>
		 */
		pluginInstallUsage: () => LocalizedString
		/**
		 * 用法：/plugin uninstall <插件ID>
		 */
		pluginUninstallUsage: () => LocalizedString
		/**
		 * 用法：/plugin install <市场>/<插件名> 或 /plugin uninstall <插件ID>
		 */
		pluginUsage: () => LocalizedString
		/**
		 * 用法：/mcp、/mcp reload 或 /mcp login <名称>
		 */
		mcpUsage: () => LocalizedString
		/**
		 * 用法：/mcp login <名称>
		 */
		mcpLoginUsage: () => LocalizedString
		/**
		 * 用法：/review [detached] [branch <分支>|commit <SHA>|custom <说明>]
		 */
		reviewUsage: () => LocalizedString
		/**
		 * 用法：/rollback 或 /rollback <回滚的 turn 数量>
		 */
		rollbackUsage: () => LocalizedString
		/**
		 * 用法：/thread name <名称> 或 /thread meta branch=<分支> sha=<提交> origin=<URL> 或 /thread clean-terminals
		 */
		threadUsage: () => LocalizedString
		/**
		 * 用法：/thread name <名称>
		 */
		threadNameUsage: () => LocalizedString
		/**
		 * 用法：/thread meta branch=<分支> sha=<提交> origin=<URL>
		 */
		threadMetaUsage: () => LocalizedString
		/**
		 * 用法：/mention <path> :: 任务说明
		 */
		mentionUsage: () => LocalizedString
		/**
		 * 用法：/attach <附件ID> :: 任务说明
		 */
		attachUsage: () => LocalizedString
		/**
		 * 用法：/local_image <图片路径> :: 任务说明
		 */
		localImageUsage: () => LocalizedString
		/**
		 * 这个问题只能用按钮回答。
		 */
		buttonsOnly: () => LocalizedString
		/**
		 * 请先切换到这个会话，再发送文字回答。
		 */
		switchSessionBeforeTextReply: () => LocalizedString
		/**
		 * 这个操作当前不支持。
		 */
		operationNotSupported: () => LocalizedString
		/**
		 * 这个问题不能跳过。
		 */
		cannotSkip: () => LocalizedString
		/**
		 * 请输入有效数字。
		 */
		invalidNumber: () => LocalizedString
		/**
		 * 请输入整数。
		 */
		integerRequired: () => LocalizedString
		/**
		 * 请输入 true/false 或 是/否。
		 */
		booleanFormat: () => LocalizedString
		/**
		 * 请至少输入一个值。
		 */
		atLeastOneValue: () => LocalizedString
		/**
		 * 请先输入至少一个值，或点击跳过。
		 */
		atLeastOneValueOrSkip: () => LocalizedString
		/**
		 * 回答不能为空。
		 */
		answerRequired: () => LocalizedString
		/**
		 * 输入值不合法。
		 */
		invalidValue: () => LocalizedString
		/**
		 * 可用值：
		 */
		allowedValuesPrefix: () => LocalizedString
		/**
		 * 。
		 */
		allowedValuesSuffix: () => LocalizedString
		/**
		 * 当前没有活动会话，请先发送 /new 或 /use 进入项目。
		 */
		browserNoSession: () => LocalizedString
		/**
		 * 当前项目目录不可用，请重新选择项目后再试。
		 */
		browserUnavailableProject: () => LocalizedString
		/**
		 * 当前浏览根目录不可用，请重新发送 /new 后重试。
		 */
		browserUnavailableRoot: () => LocalizedString
		/**
		 * 这个按钮已过期，请重新发送 /browse。
		 */
		browserExpired: () => LocalizedString
		/**
		 * 这个按钮已过期，请重新发送 /new 后再浏览。
		 */
		browserExpiredPreSession: () => LocalizedString
		/**
		 * 当前无法更新这个浏览消息，请重新发送 /browse。
		 */
		browserUpdateFailed: () => LocalizedString
		/**
		 * Phase 1 暂不支持浏览符号链接。
		 */
		browserSymlinkUnsupported: () => LocalizedString
		/**
		 * 当前目录不可用，请重新发送 /new 后重试。
		 */
		browserCreateSessionUnavailable: () => LocalizedString
		/**
		 * 暂时无法读取这个文件，请稍后重试。
		 */
		browserFileInfoFailed: () => LocalizedString
		/**
		 * 当前无法关闭这个浏览消息。
		 */
		browserCloseFailed: () => LocalizedString
		/**
		 * 暂时无法发送这张图片预览，请稍后重试。
		 */
		browserImagePreviewFailed: () => LocalizedString
		/**
		 * 模型操作暂时不可用，请稍后重试。
		 */
		modelOperationUnavailable: () => LocalizedString
		/**
		 * 技能列表暂时不可用，请稍后重试。
		 */
		skillsListUnavailable: () => LocalizedString
		/**
		 * 结构化 skill 输入暂时不可用，请稍后重试。
		 */
		structuredSkillInputUnavailable: () => LocalizedString
		/**
		 * 插件列表暂时不可用，请稍后重试。
		 */
		extensionsListUnavailable: () => LocalizedString
		/**
		 * 当前无法管理插件，请稍后重试。
		 */
		manageExtensionsUnavailable: () => LocalizedString
		/**
		 * 当前无法读取 Apps 列表，请稍后重试。
		 */
		appsListUnavailable: () => LocalizedString
		/**
		 * 当前无法读取 MCP 状态，请稍后重试。
		 */
		mcpStatusUnavailable: () => LocalizedString
		/**
		 * 当前无法读取账号状态，请稍后重试。
		 */
		accountStatusUnavailable: () => LocalizedString
		/**
		 * 当前无法启动审查，请稍后重试。
		 */
		reviewUnavailable: () => LocalizedString
		/**
		 * 当前无法分叉这个会话，请稍后重试。
		 */
		forkSessionUnavailable: () => LocalizedString
		/**
		 * 当前无法回滚这个会话，请稍后重试。
		 */
		rollbackSessionUnavailable: () => LocalizedString
		/**
		 * 当前无法清空这个会话的上下文，请稍后重试。
		 */
		clearContextUnavailable: () => LocalizedString
		/**
		 * 当前无法压缩这个线程，请稍后重试。
		 */
		compactThreadUnavailable: () => LocalizedString
		/**
		 * 本地图片输入暂时不可用，请稍后重试。
		 */
		localImageInputUnavailable: () => LocalizedString
		/**
		 * 结构化引用输入暂时不可用，请稍后重试。
		 */
		structuredReferenceInputUnavailable: () => LocalizedString
		/**
		 * 附件引用暂时不可用，请稍后重试。
		 */
		attachmentReferenceUnavailable: () => LocalizedString
		/**
		 * 当前无法更新线程设置，请稍后重试。
		 */
		threadSettingsUnavailable: () => LocalizedString
		/**
		 * 当前无法恢复 Codex 会话，请稍后重试。
		 */
		resumeSessionUnavailable: () => LocalizedString
		/**
		 * 当前无法开始实施，请稍后重试。
		 */
		implementationUnavailable: () => LocalizedString
		/**
		 * 这台服务器还没有绑定
		 */
		serverNotBoundPrefix: () => LocalizedString
		/**
		 * 账号，请等待管理员在本机确认。
		 */
		serverNotBoundSuffix: () => LocalizedString
		/**
		 * 这个
		 */
		unauthorizedAccountPrefix: () => LocalizedString
		/**
		 * 账号无权访问此服务器上的 Codex。
		 */
		unauthorizedAccountSuffix: () => LocalizedString
		/**
		 * 这个按钮已过期，请重新打开编辑器。
		 */
		buttonExpiredReopenEditor: () => LocalizedString
		/**
		 * 这个按钮已过期，请重新打开命令面板。
		 */
		buttonExpiredReopenPanel: () => LocalizedString
		/**
		 * 这个按钮已过期，请重新发送 /inspect。
		 */
		buttonExpiredInspect: () => LocalizedString
		/**
		 * 已保存，但暂时无法刷新命令面板。
		 */
		saveRefreshFailed: () => LocalizedString
		/**
		 * 暂时无法关闭这条消息，请稍后再试。
		 */
		messageCloseFailed: () => LocalizedString
		/**
		 * 详情过长，已改为纯文本发送。
		 */
		detailsSentAsText: () => LocalizedString
		/**
		 * 暂时无法更新详情，请稍后重试。
		 */
		detailsUpdateFailed: () => LocalizedString
		/**
		 * 语音输入失败：
		 */
		voiceInputFailedPrefix: () => LocalizedString
		/**
		 * 找不到附件：
		 */
		attachmentNotFoundPrefix: () => LocalizedString
		/**
		 * 以下附件未能完成解析：

		 */
		attachmentsParseFailedPrefix: () => LocalizedString
	}
	success: {
		/**
		 * 已请求停止当前操作。
		 */
		stopRequested: () => LocalizedString
		/**
		 * 已请求停止这个会话的当前操作。
		 */
		stopRequestedForSession: () => LocalizedString
		/**
		 * 已切换到会话：
		 */
		sessionSwitchedPrefix: () => LocalizedString
		/**
		 * 已保存。
		 */
		settingsSaved: () => LocalizedString
		/**
		 * 设置已保存，但消息暂时无法更新。
		 */
		settingsSavedButMessageUpdateFailed: () => LocalizedString
		/**
		 * 已恢复默认，记得保存。
		 */
		defaultsRestored: () => LocalizedString
		/**
		 * 已清空会话「
		 */
		threadClearedPrefix: () => LocalizedString
		/**
		 * 」的上下文，并立即切换到新的 Codex 线程。上一线程已保留到归档会话中，可用 /sessions archived 查看。
		 */
		threadClearedSuffix: () => LocalizedString
		/**
		 * 已重置会话「
		 */
		threadResetPrefix: () => LocalizedString
		/**
		 * 」并立即启动新的 Codex 线程。
		 */
		threadResetSuffix: () => LocalizedString
		/**
		 * 会话标题已更新为：
		 */
		threadNameUpdatedPrefix: () => LocalizedString
		/**
		 * 已为会话「
		 */
		threadMetaUpdatedPrefix: () => LocalizedString
		/**
		 * 」更新线程元数据：
		 */
		threadMetaUpdatedSuffix: () => LocalizedString
		/**
		 * 已为会话「
		 */
		terminalsCleanedPrefix: () => LocalizedString
		/**
		 * 」清理当前线程的后台终端。
		 */
		terminalsCleanedSuffix: () => LocalizedString
		/**
		 * 已为会话「
		 */
		modelSetPrefix: () => LocalizedString
		/**
		 * 」设置模型：
		 */
		modelSetSuffix: () => LocalizedString
		/**
		 * 
	下次任务开始时生效。
		 */
		modelSetEffect: () => LocalizedString
		/**
		 * 已为会话「
		 */
		planModeToggledPrefix: () => LocalizedString
		/**
		 * 」
		 */
		planModeToggledSuffix: () => LocalizedString
		/**
		 *  Plan mode。
		 */
		planModeToggledPlan: () => LocalizedString
		/**
		 * 已创建审查会话：
		 */
		reviewSessionCreatedPrefix: () => LocalizedString
		/**
		 * 已创建分叉会话：
		 */
		forkSessionCreatedPrefix: () => LocalizedString
		/**
		 * 已为会话「
		 */
		compactRequestedPrefix: () => LocalizedString
		/**
		 * 」请求压缩当前线程。
		 */
		compactRequestedSuffix: () => LocalizedString
		/**
		 * 已回滚到：
		 */
		rollbackCompletedPrefix: () => LocalizedString
		/**
		 * 已为会话「
		 */
		rollbackTurnsPrefix: () => LocalizedString
		/**
		 * 」回滚最近 
		 */
		rollbackTurnsMiddle: () => LocalizedString
		/**
		 *  个 turn。
		 */
		rollbackTurnsSuffix: () => LocalizedString
		/**
		 * 已回滚最近 
		 */
		rollbackTurnsNoSessionPrefix: () => LocalizedString
		/**
		 *  个 turn。
		 */
		rollbackTurnsNoSessionSuffix: () => LocalizedString
		/**
		 * 已为项目「
		 */
		pluginInstalledPrefix: () => LocalizedString
		/**
		 * 」安装插件：
		 */
		pluginInstalledMiddle: () => LocalizedString
		/**
		 * 已为项目「
		 */
		pluginUninstalledPrefix: () => LocalizedString
		/**
		 * 」卸载插件：
		 */
		pluginUninstalledMiddle: () => LocalizedString
		/**
		 * 已重新加载 MCP 服务器配置。
		 */
		mcpReloaded: () => LocalizedString
		/**
		 * 已生成 MCP 登录链接：
		 */
		mcpLoginLinkPrefix: () => LocalizedString
		/**
		 * 

		 */
		mcpLoginLinkMiddle: () => LocalizedString
		/**
		 * 
	完成后重新发送 /mcp 查看最新状态。
		 */
		mcpLoginLinkSuffix: () => LocalizedString
		/**
		 * 已为会话「
		 */
		planModeTogglePrefix: () => LocalizedString
		/**
		 * 」
		 */
		planModeToggleMiddle: () => LocalizedString
		/**
		 *  Plan mode。
		 */
		planModeToggleSuffix: () => LocalizedString
		/**
		 * 已取消项目别名修改。
		 */
		renameProjectCancelled: () => LocalizedString
		/**
		 * 已取消会话重命名。
		 */
		renameSessionCancelled: () => LocalizedString
		/**
		 * 已发送图片预览。
		 */
		imagePreviewSent: () => LocalizedString
		/**
		 * 已取消待发送的结构化输入。
		 */
		structuredInputCancelled: () => LocalizedString
		/**
		 * 已收到语音，
		 */
		voiceReceivedPrefix: () => LocalizedString
		/**
		 * 正在转写。
		 */
		voiceTranscribing: () => LocalizedString
		/**
		 * 正在排队转写。前方还有 
		 */
		voiceQueuedPrefix: () => LocalizedString
		/**
		 *  条语音。
		 */
		voiceQueuedSuffix: () => LocalizedString
	}
	hints: {
		/**
		 * 如需查看或刷新 Hub，可发送 /hub。
		 */
		hubCommandReminder: () => LocalizedString
		/**
		 * 需要查看运行卡片时，可发送 /hub。
		 */
		hubCommandReminderShort: () => LocalizedString
		/**
		 * 请先用 /new 选择项目，或用 /resume all 查看全部 Codex 会话。
		 */
		selectProjectOrResume: () => LocalizedString
		/**
		 * 已记录
		 */
		recordedContinueOrCancelPrefix: () => LocalizedString
		/**
		 * ，请继续发送任务说明，或发送 /cancel 取消。
		 */
		recordedContinueOrCancelSuffix: () => LocalizedString
	}
	prompts: {
		/**
		 * 请输入新的项目别名。
	发送 /cancel 取消。
		 */
		renameProject: () => LocalizedString
		/**
		 * 请输入新的会话名称。
	发送 /cancel 取消。
		 */
		renameSession: () => LocalizedString
		/**
		 * 请继续发送要和
		 */
		continueStructuredInputPrefix: () => LocalizedString
		/**
		 * 一起交给 Codex 的说明。
		 */
		continueStructuredInputSuffix: () => LocalizedString
	}
	labels: {
		/**
		 * [启用]
		 */
		enabled: () => LocalizedString
		/**
		 * [禁用]
		 */
		disabled: () => LocalizedString
		/**
		 * [已安装]
		 */
		installed: () => LocalizedString
		/**
		 * [未安装]
		 */
		notInstalled: () => LocalizedString
		/**
		 * [可访问]
		 */
		accessible: () => LocalizedString
		/**
		 * [不可访问]
		 */
		notAccessible: () => LocalizedString
		/**
		 * 可用技能
		 */
		availableSkills: () => LocalizedString
		/**
		 * 可用插件
		 */
		availablePlugins: () => LocalizedString
		/**
		 * 当前可用 Apps
		 */
		availableApps: () => LocalizedString
		/**
		 * 市场：
		 */
		marketplacePrefix: () => LocalizedString
		/**
		 * 来源插件：
		 */
		sourcePluginPrefix: () => LocalizedString
		/**
		 * 安装地址：
		 */
		installUrlPrefix: () => LocalizedString
		/**
		 * MCP 服务器状态
		 */
		mcpServerStatus: () => LocalizedString
		/**
		 * 工具 
		 */
		mcpToolsPrefix: () => LocalizedString
		/**
		 * 资源 
		 */
		mcpResourcesPrefix: () => LocalizedString
		/**
		 * 模板 
		 */
		mcpTemplatesPrefix: () => LocalizedString
		/**
		 * 当前 Codex 账号
		 */
		currentCodexAccount: () => LocalizedString
		/**
		 * 账号：未登录
		 */
		accountNotLoggedIn: () => LocalizedString
		/**
		 * 类型：API Key
		 */
		accountTypeApiKey: () => LocalizedString
		/**
		 * 类型：ChatGPT
		 */
		accountTypeChatGPT: () => LocalizedString
		/**
		 * 邮箱：
		 */
		accountEmailPrefix: () => LocalizedString
		/**
		 * 计划：
		 */
		accountPlanPrefix: () => LocalizedString
		/**
		 * 需要 OpenAI Auth
		 */
		requiresOpenaiAuth: () => LocalizedString
		/**
		 * 是
		 */
		requiresOpenaiAuthYes: () => LocalizedString
		/**
		 * 否
		 */
		requiresOpenaiAuthNo: () => LocalizedString
		/**
		 * 额度：
		 */
		rateLimitQuotaPrefix: () => LocalizedString
		/**
		 * 限额计划：
		 */
		rateLimitPlanPrefix: () => LocalizedString
		/**
		 *  分钟
		 */
		rateLimitWindowMinutesSuffix: () => LocalizedString
		/**
		 * 当前窗口
		 */
		rateLimitWindowCurrent: () => LocalizedString
		/**
		 * 主额度使用：
		 */
		rateLimitPrimaryUsagePrefix: () => LocalizedString
		/**
		 * %（
		 */
		rateLimitPrimaryUsageMiddle: () => LocalizedString
		/**
		 * ）
		 */
		rateLimitPrimaryUsageSuffix: () => LocalizedString
		/**
		 * Credits：
		 */
		creditsPrefix: () => LocalizedString
		/**
		 * Credits：无限
		 */
		creditsUnlimited: () => LocalizedString
		/**
		 * 可用
		 */
		creditsAvailable: () => LocalizedString
		/**
		 * 不可用
		 */
		creditsUnavailable: () => LocalizedString
		/**
		 * skill：
		 */
		skillLabelPrefix: () => LocalizedString
		/**
		 * 语音：
		 */
		voiceInputPrefix: () => LocalizedString
		/**
		 * 图片输入
		 */
		imageInput: () => LocalizedString
		/**
		 * 结构化输入
		 */
		structuredInput: () => LocalizedString
		/**
		 * 引用：
		 */
		referencePrefix: () => LocalizedString
		/**
		 * 本地图片：
		 */
		localImagePrefix: () => LocalizedString
		/**
		 * 附件：
		 */
		attachmentPrefix: () => LocalizedString
		/**
		 *  张图片
		 */
		multipleImagesSuffix: () => LocalizedString
		/**
		 * 图片
		 */
		image: () => LocalizedString
		/**
		 * 清空前：
		 */
		preClearPrefix: () => LocalizedString
		/**
		 * 扫描警告：
		 */
		scanWarningPrefix: () => LocalizedString
		/**
		 * 使用 /skill <技能名> :: 任务说明 将 skill 作为结构化输入发送给 Codex。
		 */
		skillUsage: () => LocalizedString
		/**
		 * 使用 /plugin install <市场>/<插件名> 安装插件。
		 */
		pluginInstallUsage: () => LocalizedString
		/**
		 * 使用 /plugin uninstall <插件ID> 卸载插件。
		 */
		pluginUninstallUsage: () => LocalizedString
		/**
		 * 例如：/plugin install 
		 */
		pluginInstallExamplePrefix: () => LocalizedString
		/**
		 * 使用 /mcp reload 重新加载配置，或 /mcp login <名称> 启动 OAuth 登录。
		 */
		mcpUsage: () => LocalizedString
		/**
		 * 上一级
		 */
		parentDirectory: () => LocalizedString
		/**
		 * 在当前目录新建
		 */
		createSessionHere: () => LocalizedString
		/**
		 * 刷新
		 */
		refresh: () => LocalizedString
		/**
		 * MCP 工具
		 */
		mcpTool: () => LocalizedString
		/**
		 * 当前会话：
		 */
		currentSessionPrefix: () => LocalizedString
		/**
		 * 当前项目：
		 */
		currentProjectPrefix: () => LocalizedString
		/**
		 * 开启
		 */
		planModeOn: () => LocalizedString
		/**
		 * 关闭
		 */
		planModeOff: () => LocalizedString
		/**
		 * 当前任务不受影响，下次任务开始时生效。
		 */
		planModeNextTaskEffect: () => LocalizedString
		/**
		 * 下次任务开始时生效。
		 */
		planModeNextTaskEffectOnly: () => LocalizedString
		/**
		 * 语音转写：
		 */
		voiceTranscriptionPrefix: () => LocalizedString
		/**
		 * 请逐字转写收到的语音，只返回转写文本，不要解释。
		 */
		voiceRealtimeTranscriptionPrompt: () => LocalizedString
		/**
		 * 已接收文件附件：

		 */
		attachmentReceivedSinglePrefix: () => LocalizedString
		/**
		 * 
	下一条消息会自动带上最近附件；也可用 /attach <附件ID> :: 任务说明；发送 /cancel 可取消。
		 */
		attachmentReceivedSingleSuffix: () => LocalizedString
		/**
		 * 已接收 
		 */
		attachmentReceivedMultiplePrefix: () => LocalizedString
		/**
		 *  个文件附件：

		 */
		attachmentReceivedMultipleMiddle: () => LocalizedString
		/**
		 * 
	下一条消息会自动带上最近附件；也可用 /attach <附件ID> :: 任务说明；发送 /cancel 可取消。
		 */
		attachmentReceivedMultipleSuffix: () => LocalizedString
		/**
		 * 以下是附件《
		 */
		attachmentExtractContentPrefix: () => LocalizedString
		/**
		 * 》的提取内容：


		 */
		attachmentExtractContentMiddle: () => LocalizedString
		/**
		 * 以下是附件《
		 */
		attachmentExtractContentTruncatedPrefix: () => LocalizedString
		/**
		 * 》的提取内容（已截断）：


		 */
		attachmentExtractContentTruncatedMiddle: () => LocalizedString
	}
	statuses: {
		/**
		 * 已完成
		 */
		completed: () => LocalizedString
		/**
		 * 失败
		 */
		failed: () => LocalizedString
		/**
		 * 已中断
		 */
		interrupted: () => LocalizedString
		/**
		 * 空闲
		 */
		idle: () => LocalizedString
		/**
		 * 执行中
		 */
		running: () => LocalizedString
		/**
		 * 不支持认证
		 */
		authNotSupported: () => LocalizedString
		/**
		 * 未登录
		 */
		notLoggedIn: () => LocalizedString
		/**
		 * 上次运行因桥重启而停止
		 */
		stoppedByBridgeRestart: () => LocalizedString
	}
	notices: {
		/**
		 * Codex 配置警告：
		 */
		configWarningPrefix: () => LocalizedString
		/**
		 * Codex 弃用提示：
		 */
		deprecationWarningPrefix: () => LocalizedString
		/**
		 * Codex 已调整模型：
		 */
		modelAdjustedPrefix: () => LocalizedString
		/**
		 *  -> 
		 */
		modelAdjustedArrow: () => LocalizedString
		/**
		 *  (
		 */
		modelAdjustedReasonPrefix: () => LocalizedString
		/**
		 * )
		 */
		modelAdjustedReasonSuffix: () => LocalizedString
		/**
		 * Codex 技能列表已刷新。
		 */
		skillsRefreshed: () => LocalizedString
		/**
		 * Codex 线程上下文已压缩。
		 */
		threadCompacted: () => LocalizedString
	}
	help: {
		/**
		 * 用法：/review [detached] [branch <分支>|commit <SHA>|custom <说明>]
		 */
		reviewUsage: () => LocalizedString
		/**
		 * 用法：/thread name <名称> 或 /thread meta branch=<分支> sha=<提交> origin=<URL> 或 /thread clean-terminals
		 */
		threadUsage: () => LocalizedString
	}
	warnings: {
		/**
		 * 注意：这不会自动撤销代理已经写到本地文件的改动。
		 */
		rollbackNoAutoRevert: () => LocalizedString
		/**
		 * 这些 App 可能还需要额外授权：
		 */
		appsNeedAuthorization: () => LocalizedString
		/**
		 * 扫描警告：
		 */
		scanErrorPrefix: () => LocalizedString
	}
	input: {
		/**
		 * 是
		 */
		yes: () => LocalizedString
		/**
		 * 否
		 */
		no: () => LocalizedString
	}
	feishu: {
		/**
		 * 帮助
		 */
		help: () => LocalizedString
		/**
		 * 新建会话
		 */
		newSession: () => LocalizedString
		/**
		 * 当前状态
		 */
		status: () => LocalizedString
		/**
		 * 最近会话
		 */
		sessions: () => LocalizedString
		/**
		 * 中断操作
		 */
		interrupt: () => LocalizedString
		/**
		 * 查看详情
		 */
		inspect: () => LocalizedString
		/**
		 * 运行卡
		 */
		hub: () => LocalizedString
	}
}

export type Formatters = {}
